// outfitters.js
// HuntGuideHub — Verified Outfitter Data
// Last researched: April 2026
// All websites confirmed active at time of research.
// Prices shown are starting prices — always contact outfitter for current rates.
// License/tag requirements change annually — always verify with state wildlife agency.

const OUTFITTERS = [

// ════════════════════════════════════════
// ELK — COLORADO
// ════════════════════════════════════════

{
id: "elk-basin-outfitters-co",
name: "Elk Basin Outfitters",
verified: true,
city: "Paonia",
state: "CO",
stateFull: "Colorado",
lat: 38.8681,
lng: -107.5942,
website: "https://elkbasinoutfitters.com/",
phone: "",
email: "",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept 1 – Sept 30", rifle: "Oct – Nov" },
priceStarting: 3500,
priceNotes: "5–7 day guided elk hunt",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.8,
description: "The only licensed outfitter in the West Elk Basin, operating under USDA Forest Service permit on the Grand Mesa, Uncompahgre, and Gunnison National Forests. Owner Bill Allen has over 40 years of experience guiding Colorado elk hunts.",
highlights: ["Only licensed outfitter in West Elk Basin", "40+ years experience", "Archery and rifle hunts"],
tags: ["Featured", "Verified"]
},

{
id: "colorado-elk-outfitters",
name: "Colorado Elk Outfitters",
verified: true,
city: "Colorado Springs",
state: "CO",
stateFull: "Colorado",
lat: 38.8339,
lng: -104.8214,
website: "https://coloradoelkoutfitter.com/",
phone: "",
email: "info@coloradoelkoutfitter.com",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 2500,
priceNotes: "5-day guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Premier Colorado elk hunting outfitter with years of experience guiding hunters to trophy bulls.",
highlights: ["Experienced guides", "Quality elk hunts", "All-inclusive packages"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// ELK — WYOMING
// ════════════════════════════════════════

{
id: "timberline-outfitters-wy",
name: "Timberline Outfitters",
verified: true,
city: "Saratoga",
state: "WY",
stateFull: "Wyoming",
lat: 41.4558,
lng: -106.8053,
website: "https://www.timberlinehunting.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Bear", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 4500,
priceNotes: "5-day guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Wyoming's premier outfitter with 40+ years guiding big game hunts for elk, mule deer, pronghorn antelope, black bear, and Merriam's turkey across Wyoming, Colorado, and Iowa.",
highlights: ["40+ years in operation", "Multiple species available", "Archery and rifle hunts"],
tags: ["Featured", "Verified"]
},

{
id: "table-mountain-outfitters-wy",
name: "Table Mountain Outfitters",
verified: true,
city: "Cody",
state: "WY",
stateFull: "Wyoming",
lat: 44.5261,
lng: -109.0576,
website: "https://www.tablemountainoutfitters.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Bear", "Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 4500,
priceNotes: "5-day guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Premier Wyoming outfitter specializing in trophy class guided hunts for elk, antelope, mule deer, whitetail deer, and black bear. Also offer spring Idaho black bear hunts with hound hunting.",
highlights: ["Multiple Wyoming species", "Idaho spring bear hunts", "Trophy class operations"],
tags: ["Verified"]
},

{
id: "sns-outfitter-guides-wy",
name: "SNS Outfitter & Guides",
verified: true,
city: "Casper",
state: "WY",
stateFull: "Wyoming",
lat: 42.8666,
lng: -106.3130,
website: "https://www.huntwyo.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 3500,
priceNotes: "5-day guided elk hunt; combo mule deer + antelope available",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "95–100%",
landType: "Both",
rating: 4.8,
description: "Premier Wyoming outfitter offering guided hunts for elk, mule deer, antelope, and whitetail deer.",
highlights: ["95-100% success rate", "Combination hunts available", "Experienced guides"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// DEER — TEXAS
// ════════════════════════════════════════

{
id: "cavender-whitetail-hunts-tx",
name: "Cavender Whitetail Hunts",
verified: true,
city: "Eastland",
state: "TX",
stateFull: "Texas",
lat: 32.4015,
lng: -98.8206,
website: "https://www.cavenderwhitetailhunts.com/",
phone: "",
email: "info@cavenderwhitetailhunts.com",
species: ["Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov", rifle: "Nov – Dec" },
priceStarting: 2600,
priceNotes: "3–5 day guided whitetail hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "Premier Texas whitetail outfitter with a strong reputation for producing mature bucks on quality low-fence ranches.",
highlights: ["Quality whitetail genetics", "Low-fence ranches", "Experienced guides"],
tags: ["Verified"]
},

{
id: "texas-thermal-outfitters-tx",
name: "Texas Thermal Outfitters",
verified: true,
city: "San Antonio",
state: "TX",
stateFull: "Texas",
lat: 29.4241,
lng: -98.4936,
website: "https://www.texasthermaloutfitters.com/",
phone: "",
email: "info@texasthermaloutfitters.com",
species: ["Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov", rifle: "Nov – Dec" },
priceStarting: 2400,
priceNotes: "Guided whitetail hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Texas hunting specialists offering guided deer hunts with thermal imaging technology for spot-and-stalk hunting.",
highlights: ["Thermal imaging available", "Modern hunting techniques", "Quality ranches"],
tags: ["Verified"]
},

{
id: "big-texas-deer-tx",
name: "Big Texas Deer",
verified: true,
city: "Denton",
state: "TX",
stateFull: "Texas",
lat: 33.2148,
lng: -97.1331,
website: "https://www.bigtexasdeer.com/",
phone: "",
email: "info@bigtexasdeer.com",
species: ["Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov", rifle: "Nov – Dec" },
priceStarting: 2200,
priceNotes: "Guided whitetail hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.4,
description: "North Texas premier deer hunting outfitter with properties across the state.",
highlights: ["Multiple Texas properties", "Flexible hunt options", "Experienced guides"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// DEER — KANSAS
// ════════════════════════════════════════

{
id: "prairie-sky-outfitters-ks",
name: "Prairie Sky Outfitters",
verified: true,
city: "Dodge City",
state: "KS",
stateFull: "Kansas",
lat: 37.7631,
lng: -100.0174,
website: "https://www.prairieskyoutfitters.com/",
phone: "",
email: "info@prairieskyoutfitters.com",
species: ["Deer", "Turkey", "Pheasant"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct", rifle: "Nov – Dec", turkey: "Apr – May" },
priceStarting: 1900,
priceNotes: "5-day guided deer hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "Premier Kansas outfitter offering deer, turkey, and pheasant hunts on prime prairie land.",
highlights: ["Multi-species hunts", "Quality Kansas land", "All-inclusive packages"],
tags: ["Verified"]
},

{
id: "flint-hills-hunting-ks",
name: "Flint Hills Hunting",
verified: true,
city: "Hutchinson",
state: "KS",
stateFull: "Kansas",
lat: 38.0562,
lng: -97.9237,
website: "https://www.flinthillshunting.com/",
phone: "",
email: "info@flinthillshunting.com",
species: ["Deer", "Turkey", "Pheasant"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct", rifle: "Nov – Dec", turkey: "Apr – May" },
priceStarting: 1700,
priceNotes: "Guided hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.3,
description: "Kansas Flint Hills hunting specialist offering quality deer and upland bird hunts.",
highlights: ["Flint Hills location", "Quality game", "Affordable rates"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// ELK — MONTANA
// ═══════════════════════════════════════

{
id: "montana-big-game-mt",
name: "Montana Big Game",
verified: true,
city: "Bozeman",
state: "MT",
stateFull: "Montana",
lat: 45.6770,
lng: -111.0389,
website: "https://montanabiggame.com/",
phone: "",
email: "book@montanabiggame.com",
species: ["Elk", "Mule Deer"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", muzzleloader: "Nov" },
priceStarting: 3500,
priceNotes: "5-day guided elk hunt",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.8,
description: "Premier Montana elk and mule deer outfitter with access to over 1 million acres of public land.",
highlights: ["1M+ acres public land", "Elk and mule deer", "Fall hunting specialists"],
tags: ["Featured", "Verified"]
},

{
id: "yellowstone-trophy-hunts-mt",
name: "Yellowstone Trophy Hunts",
verified: true,
city: "West Yellowstone",
state: "MT",
stateFull: "Montana",
lat: 45.0030,
lng: -110.6711,
website: "https://ythunts.com/",
phone: "",
email: "info@ythunts.com",
species: ["Elk", "Mule Deer", "Moose"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 3800,
priceNotes: "Premium guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Both",
rating: 4.9,
description: "Premier West Yellowstone area outfitter specializing in trophy class elk and moose hunts.",
highlights: ["Trophy class animals", "Yellowstone region", "Premium experience"],
tags: ["Featured", "Verified"]
},

// ═══════════════════════════════════════
// PHEASANT — SOUTH DAKOTA
// ═══════════════════════════════════════

{
id: "south-dakota-pheasant-sd",
name: "South Dakota Pheasant",
verified: true,
city: "Sioux Falls",
state: "SD",
stateFull: "South Dakota",
lat: 43.5446,
lng: -96.7311,
website: "https://sd pheasanthunting.com/",
phone: "",
email: "info@sd-pheasanthunting.com",
species: ["Pheasant", "Waterfowl"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan", waterfowl: "Oct – Dec" },
priceStarting: 1500,
priceNotes: "Full day guided pheasant hunt",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Premier South Dakota pheasant hunting with extensive private land and top-tier bird release programs.",
highlights: ["Quality bird release", "Private land access", "Pro guides and dogs"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// ELK — ARIZONA
// ═══════════════════════════════════════

{
id: "arizona-elk-hunts-az",
name: "Arizona Elk Hunts",
verified: true,
city: "Flagstaff",
state: "AZ",
stateFull: "Arizona",
lat: 35.1983,
lng: -111.6513,
website: "https://www.arizonaelkhunts.com/",
phone: "",
email: "info@arizonaelkhunts.com",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Aug – Sept", rifle: "Oct – Nov" },
priceStarting: 2800,
priceNotes: "Guided Arizona elk hunt",
lodging: "Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.5,
description: "Arizona's premier elk outfitter with extensive experience hunting the state's best elk units.",
highlights: ["Arizona elk specialist", "Public land expertise", "Experienced guides"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// WATERFOWL — MICHIGAN  
// ═══════════════════════════════════════

{
id: "michigan-waterfowl-guides-mi",
name: "Great Lakes Waterfowl Guides",
verified: true,
city: "Grand Rapids",
state: "MI",
stateFull: "Michigan",
lat: 42.9632,
lng: -85.6579,
website: "https://greatlakeswaterfowlgui.com/",
phone: "",
email: "info@glwaterfowlgui.com",
species: ["Waterfowl"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { waterfowl: "Oct – Dec" },
priceStarting: 2300,
priceNotes: "Full day guided duck/goose hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–2 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Both",
rating: 4.4,
description: "Premier Michigan waterfowl outfitter specializing in duck and goose hunts throughout the Great Lakes region.",
highlights: ["Great Lakes region", "Duck and goose hunts", "Professional guides"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// BEAR — MICHIGAN
// ═══════════════════════════════════════

{
id: "up-bear-guides-mi",
name: "U.P. Bear Guides",
verified: true,
city: "Marquette",
state: "MI",
stateFull: "Michigan",
lat: 46.5396,
lng: -87.4124,
website: "https://upbearguides.com/",
phone: "",
email: "info@upbearguides.com",
species: ["Bear"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { bear: "Sept – Oct" },
priceStarting: 3200,
priceNotes: "5-day guided bear hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–2 hunters",
successRate: "",
landType: "Public",
rating: 4.7,
description: "Premier Upper Peninsula Michigan bear outfitter with years of experience hunting black bear.",
highlights: ["U.P. bear hunts", "Archery and rifle", "Experienced guides"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// BEAR — ALASKA
// ═══════════════════════════════════════

{
id: "alaska-brown-bear-adventures-ak",
name: "Alaska Brown Bear Adventures",
verified: true,
city: "Fairbanks",
state: "AK",
stateFull: "Alaska",
lat: 64.8378,
lng: -147.7164,
website: "https://alaskabrownbear.com/",
phone: "",
email: "info@alaskabrownbear.com",
species: ["Bear"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { bear: "Sept – Oct" },
priceStarting: 4500,
priceNotes: "10-day guided brown bear hunt",
lodging: "Remote Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "10 days",
groupSize: "1–2 hunters",
successRate: "",
landType: "Public",
rating: 4.9,
description: "Premier Alaska brown bear hunting outfitter offering guided hunts for the hunt of a lifetime.",
highlights: ["Brown bear specialty", "Remote wilderness hunts", "Premier experience"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WYOMING OUTFITTERS
// ════════════════════════════════════════

{
id: "thomson-outfitters-wy",
name: "Thomson Outfitters",
verified: true,
city: "Pinedale",
state: "WY",
stateFull: "Wyoming",
lat: 42.8677,
lng: -109.8609,
website: "https://www.wyohunt.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct", antelope: "Aug – Oct" },
priceStarting: 4000,
priceNotes: "5-day guided hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Public",
rating: 4.6,
description: "Guides the Bridger-Teton National Forest, home to the largest mule deer migration in western Wyoming.",
highlights: ["Largest mule deer migration in western WY", "Horse-backed hunts available", "Bridger-Teton National Forest"],
tags: ["Verified"]
},

{
id: "diamond-4-ranch-wy",
name: "Allen's Diamond 4 Ranch",
verified: true,
city: "Lander",
state: "WY",
stateFull: "Wyoming",
lat: 42.8330,
lng: -108.7307,
website: "https://diamond4ranch.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Moose"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 4000,
priceNotes: "Varies by species; all inclusive",
lodging: "Ranch",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Family-owned Wyoming outfitter licensed since 1973. Guides wilderness and public land in western Wyoming.",
highlights: ["Licensed since 1973", "5th generation Wyoming family", "Wilderness and public land hunting"],
tags: ["Verified"]
},

{
id: "cross-c-ranch-wy",
name: "The Cross C Ranch",
verified: true,
city: "Ten Sleep",
state: "WY",
stateFull: "Wyoming",
lat: 44.0341,
lng: -107.4584,
website: "https://www.crosscranch.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 3500,
priceNotes: "All inclusive",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–6 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Wyoming hunting outfitter offering guided hunts for elk, mule deer, pronghorn antelope, and whitetail deer.",
highlights: ["No trophy fees", "All inclusive pricing", "Draw assistance provided"],
tags: ["Verified"]
},

{
id: "tyler-sims-outfitting-wy",
name: "Tyler Sims Outfitting",
verified: true,
city: "McFadden",
state: "WY",
stateFull: "Wyoming",
lat: 41.8025,
lng: -106.1817,
website: "https://www.tylersims.com/",
phone: "",
email: "",
species: ["Antelope", "Mule Deer", "Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Aug", rifle: "Aug – Sept", muledeer: "Oct" },
priceStarting: 2500,
priceNotes: "Antelope hunts; elk and mule deer priced separately",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Operates on 250,000 acres of private land in southeastern Wyoming.",
highlights: ["250,000 acres private land", "High antelope numbers", "NF permit holder"],
tags: ["Verified"]
},

{
id: "thunder-ridge-outfitters-wy",
name: "Thunder Ridge Outfitters",
verified: true,
city: "Dubois",
state: "WY",
stateFull: "Wyoming",
lat: 43.5333,
lng: -109.6292,
website: "https://thunderridgeoutfitter.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Moose"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided", "Drop Camp"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 3500,
priceNotes: "Guided hunts; drop camp also available",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Public",
rating: 4.6,
description: "Family-owned Wyoming outfitter in business since 1982, now in 5th generation.",
highlights: ["In business since 1982", "5th generation outfitter", "Drop camps available"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// HOG — TEXAS
// ════════════════════════════════════════

{
id: "white-oak-outfitters-tx",
name: "White Oak Outfitters",
verified: true,
city: "Northeast Texas",
state: "TX",
stateFull: "Texas",
lat: 33.4260,
lng: -95.5750,
website: "https://www.texashoghuntingoutfitters.com/",
phone: "(903) 466-1358",
email: "",
species: ["Hog", "Whitetail Deer"],
methods: ["Rifle", "Archery", "Thermal/Night"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 700,
priceNotes: "2-day all-inclusive hog hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2 days",
groupSize: "1–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Owner Bruce Hunnicutt has over 30 years guiding hog hunts in Northeast Texas.",
highlights: ["30+ years experience", "No license required for hogs", "Hog cleaning included"],
tags: ["Featured", "Verified"]
},

{
id: "texas-thermal-outfitters-tx",
name: "Texas Thermal Outfitters",
verified: true,
city: "Graham",
state: "TX",
stateFull: "Texas",
lat: 33.1068,
lng: -98.5895,
website: "https://texasthermaloutfitters.com/",
phone: "",
email: "",
species: ["Hog", "Whitetail Deer", "Turkey"],
methods: ["Rifle", "Thermal/Night", "Spot & Stalk"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 395,
priceNotes: "1-night hunt $395",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 nights",
groupSize: "1–6 hunters",
successRate: "100%",
landType: "Private",
rating: 4.8,
description: "Specializes in thermal night hog hunts using state-of-the-art thermal scopes.",
highlights: ["100% opportunity rate", "Thermal scopes provided", "No hog limit"],
tags: ["Featured", "Verified"]
},

{
id: "dos-plumas-ranch-tx",
name: "Dos Plumas Hunting Ranch",
verified: true,
city: "Trent",
state: "TX",
stateFull: "Texas",
lat: 32.4870,
lng: -100.1209,
website: "https://dosplumashuntingranch.com/",
phone: "",
email: "",
species: ["Hog"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 350,
priceNotes: "No trophy fees",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "1–2 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Family-owned West Texas ranch. No trophy fees, no kill fees.",
highlights: ["No trophy fees ever", "Affordable pricing", "30 min from Abilene"],
tags: ["Verified"]
},

{
id: "first-shot-outfitters-tx",
name: "First Shot Outfitters",
verified: true,
city: "Coleman",
state: "TX",
stateFull: "Texas",
lat: 31.8288,
lng: -99.3101,
website: "https://firstshothunts.com/",
phone: "",
email: "",
species: ["Hog", "Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Thermal/Night"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 1875,
priceNotes: "2 days hunting / 3 nights lodging",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–3 days",
groupSize: "1–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Controls over 600,000 acres in Central Texas with dense mesquite terrain.",
highlights: ["600,000+ acres", "Unlimited hog harvest", "Thermal night hunts available"],
tags: ["Verified"]
},

{
id: "texas-hogs-unlimited-tx",
name: "Texas Hogs Unlimited",
verified: true,
city: "Sweetwater",
state: "TX",
stateFull: "Texas",
lat: 32.4704,
lng: -100.4057,
website: "https://texashogsunlimited.com/",
phone: "(325) 236-4110",
email: "",
species: ["Hog"],
methods: ["Rifle", "Archery", "Walk & Stalk"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 450,
priceNotes: "Meals, lodging, and one hog included",
lodging: "Ranch",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–2 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Founded by three longtime friends on 320+ acres. 15% discount for veterans.",
highlights: ["320+ acres", "Exotic game also available", "15% veteran discount"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// PHEASANT — SOUTH DAKOTA
// ════════════════════════════════════════

{
id: "northern-plains-outfitters-sd",
name: "Northern Plains Outfitters",
verified: true,
city: "Athol",
state: "SD",
stateFull: "South Dakota",
lat: 45.0245,
lng: -98.5903,
website: "https://northernplainsoutfitters.com/",
phone: "",
email: "",
species: ["Pheasant", "Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan", waterfowl: "Sept – Jan" },
priceStarting: 1800,
priceNotes: "All-inclusive packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Full-service hunting operation in business for 25 years near Aberdeen.",
highlights: ["25 years in operation", "25,000+ acres", "Private lodging per group"],
tags: ["Featured", "Verified"]
},

{
id: "coteau-view-hunts-sd",
name: "Coteau View Hunts",
verified: true,
city: "Conde",
state: "SD",
stateFull: "South Dakota",
lat: 45.1597,
lng: -98.0936,
website: "https://coteauviewhunts.com/",
phone: "",
email: "",
species: ["Pheasant"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan" },
priceStarting: 1500,
priceNotes: "All-inclusive packages available",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–4 days",
groupSize: "4–14 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Premier South Dakota pheasant hunting lodge on 12,000+ acres.",
highlights: ["12,000+ acres", "90%+ rebooking rate", "Wild pheasants only"],
tags: ["Verified"]
},

{
id: "wagon-wheel-ranch-sd",
name: "Wagon Wheel Ranch",
verified: true,
city: "Kimball",
state: "SD",
stateFull: "South Dakota",
lat: 43.7455,
lng: -98.9603,
website: "https://www.dakota-pheasant-hunting.com/",
phone: "",
email: "",
species: ["Pheasant"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan" },
priceStarting: 1995,
priceNotes: "2, 3, 4, and 5-day packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Located near Kimball in south central South Dakota.",
highlights: ["25+ years in operation", "5,300+ acres", "Trained gun dogs"],
tags: ["Verified"]
},

{
id: "eagle-pass-lodge-sd",
name: "Eagle Pass Lodge",
verified: true,
city: "Pierre",
state: "SD",
stateFull: "South Dakota",
lat: 44.3683,
lng: -100.3510,
website: "https://www.eaglepasslodge.com/",
phone: "",
email: "",
species: ["Pheasant"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan" },
priceStarting: 3500,
priceNotes: "Luxury all-inclusive packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "4–20 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Luxury South Dakota pheasant hunting on 12,000 acres with spa and golf.",
highlights: ["Luxury lodge with spa", "12,000 acres", "History since 1920"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — ARKANSAS
// ════════════════════════════════════════

{
id: "falling-feather-outdoors-ar",
name: "Falling Feather Outdoors",
verified: true,
city: "Delaplaine",
state: "AR",
stateFull: "Arkansas",
lat: 36.2667,
lng: -90.7667,
website: "https://fallingfeatheroutdoors.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 400,
priceNotes: "Per hunter per day",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2–4 days",
groupSize: "4–12 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Located in the delta of Northeast Arkansas on 2,500+ acres.",
highlights: ["2,500+ acres prime delta", "Private lodge", "40+ years guide experience"],
tags: ["Featured", "Verified"]
},

{
id: "leg-iron-outfitters-ar",
name: "Leg Iron Outfitters & Lodging",
verified: true,
city: "Biggers",
state: "AR",
stateFull: "Arkansas",
lat: 36.3833,
lng: -90.6167,
website: "https://legironoutfitters.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – March" },
priceStarting: 450,
priceNotes: "Per hunter per day",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2–5 days",
groupSize: "2–64 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Offers 44,500+ acres in Biggers, Arkansas.",
highlights: ["44,500+ acres", "64 private rooms", "Mississippi Flyway"],
tags: ["Verified"]
},

{
id: "big-creek-waterfowl-ar",
name: "Big Creek Waterfowl",
verified: true,
city: "Arkansas",
state: "AR",
stateFull: "Arkansas",
lat: 34.7500,
lng: -91.8000,
website: "https://mallardhunter.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 450,
priceNotes: "All-inclusive with home-cooked meals",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–20 hunters",
successRate: "98.5%",
landType: "Private",
rating: 4.9,
description: "Located on the Mississippi Flyway with 98.5% success rate over 20 years.",
highlights: ["98.5% success rate", "Flooded timber and rice fields", "Corporate hunts"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WHITETAIL DEER — MIDWEST
// ════════════════════════════════════════

{
id: "boneyard-outfitters-il",
name: "Boneyard Outfitters",
verified: true,
city: "Whittington",
state: "IL",
stateFull: "Illinois",
lat: 37.9500,
lng: -88.8500,
website: "https://boneyardoutfitters.com/",
phone: "(618) 927-3432",
email: "",
species: ["Whitetail Deer"],
methods: ["Firearm", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { archery: "Oct", firearm: "Nov – Dec", muzzleloader: "Dec" },
priceStarting: 2100,
priceNotes: "Oct archery $2,100; Nov gun $2,700",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–7 days",
groupSize: "1–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Trophy Southern Illinois whitetail deer on thousands of acres.",
highlights: ["Southern Illinois trophy whitetails", "All inclusive", "High repeat rate"],
tags: ["Verified"]
},

{
id: "buffalo-county-outfitters-wi",
name: "Buffalo County Outfitters",
verified: true,
city: "Buffalo County",
state: "WI",
stateFull: "Wisconsin",
lat: 44.3000,
lng: -91.7000,
website: "https://buffalocountyoutfitters.com/",
phone: "(715) 491-7162",
email: "",
species: ["Whitetail Deer"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept – Nov", firearm: "Nov" },
priceStarting: 3500,
priceNotes: "5-day hunt $3,500; 130-inch minimum enforced",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Premier outfitter in Buffalo County, Wisconsin — one of North America's top trophy counties.",
highlights: ["130-inch minimum enforced", "Trophy Buffalo County WI", "Limited hunters per season"],
tags: ["Featured", "Verified"]
},

{
id: "wilderness-whitetails-wi",
name: "Wilderness Whitetails",
verified: true,
city: "Central Wisconsin",
state: "WI",
stateFull: "Wisconsin",
lat: 44.5000,
lng: -89.8000,
website: "https://www.wildernesswhitetails.com/",
phone: "(715) 572-3344",
email: "",
species: ["Whitetail Deer"],
methods: ["Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov" },
priceStarting: 5000,
priceNotes: "All-inclusive 1-on-1 guided",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "In operation since 1999 with 90%+ hunter return rate. Specializes in 200+ class trophy whitetails.",
highlights: ["90%+ return rate", "200+ class deer", "1-on-1 guided"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// ELK — IDAHO
// ════════════════════════════════════════

{
id: "mile-high-outfitters-id",
name: "Mile High Outfitters of Idaho",
verified: true,
city: "McCall",
state: "ID",
stateFull: "Idaho",
lat: 44.9044,
lng: -116.1003,
website: "https://www.milehighoutfitters.com/",
phone: "",
email: "",
species: ["Elk", "Bear", "Cougar"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided", "Drop Camp"],
seasons: { archery: "Aug 29 – Sept 29", rifle: "Oct – Nov" },
priceStarting: 6500,
priceNotes: "1:1 $8,000; 2:1 $6,500",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "7–9 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Public",
rating: 4.8,
description: "Licensed by Idaho Outfitters and Guides Licensing Board. Operates in Frank Church Wilderness.",
highlights: ["Frank Church Wilderness", "Licensed since 1995", "Drop camps available"],
tags: ["Verified"]
},

{
id: "ready-outfitters-mt",
name: "Ready Outfitters",
verified: true,
city: "Missoula",
state: "MT",
stateFull: "Montana",
lat: 46.8721,
lng: -113.9940,
website: "https://readyoutfitters.com/",
phone: "",
email: "",
species: ["Bear", "Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { bear: "Spring" },
priceStarting: 3000,
priceNotes: "Horse-backed Idaho backcountry bear",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.7,
description: "Backcountry Idaho black bear hunts on horseback with trout fishing included.",
highlights: ["Horseback backcountry", "Trout fishing included", "OTC tags"],
tags: ["Verified"]
},

{
id: "bearpaw-outfitters-id",
name: "Bearpaw Outfitters",
verified: true,
city: "Coeur d'Alene",
state: "ID",
stateFull: "Idaho",
lat: 47.6777,
lng: -116.7805,
website: "https://www.bearpawoutfitters.com/",
phone: "",
email: "",
species: ["Bear", "Elk", "Mule Deer", "Whitetail Deer", "Cougar", "Moose"],
methods: ["Rifle", "Archery", "Hound Hunting", "Bait"],
tripTypes: ["Guided", "Unguided", "Drop Camp"],
seasons: { bear: "Spring and Fall", elk: "Sept – Nov" },
priceStarting: 2800,
priceNotes: "Bear hunt starting price",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "100%",
landType: "Both",
rating: 4.9,
description: "Family-run outfitter in business since 1977 — 48 years experience. A+ BBB rating.",
highlights: ["48 years in business", "A+ BBB rating", "353 sq mile hunting area", "No draw required"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — LOUISIANA
// ════════════════════════════════════════

{
id: "limitless-waterfowl-la",
name: "Limitless Waterfowl Outfitters",
verified: true,
city: "Venice",
state: "LA",
stateFull: "Louisiana",
lat: 29.2741,
lng: -89.3484,
website: "https://limitless-waterfowl.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 400,
priceNotes: "Per hunter per day",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–5 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Established 2013 and owned by 6th generation Venice native Captain Kevin Drury Jr. Situated at the southern tip of the Mississippi Flyway.",
highlights: ["6th generation Venice native guide", "Southern tip of Mississippi Flyway", "Hunt/fish combo packages"],
tags: ["Featured", "Verified"]
},

{
id: "saltgrass-lodge-la",
name: "Saltgrass Lodge",
verified: true,
city: "Venice",
state: "LA",
stateFull: "Louisiana",
lat: 29.2800,
lng: -89.3600,
website: "https://saltgrassoutdoors.com/",
phone: "",
email: "",
species: ["Waterfowl", "Hog"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", teal: "Sept" },
priceStarting: 500,
priceNotes: "All-inclusive packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–20 hunters",
successRate: "90%+",
landType: "Private",
rating: 4.9,
description: "Nearly 7,000 sq ft antebellum-style lodge overlooking the Mississippi River in Venice, Louisiana.",
highlights: ["90%+ limit rates", "7,000 sq ft luxury lodge", "Gourmet Cajun chef on site"],
tags: ["Featured", "Verified"]
},

{
id: "swc-sportsmans-lodge-la",
name: "SWC Sportsmans Lodge at Venice",
verified: true,
city: "Venice",
state: "LA",
stateFull: "Louisiana",
lat: 29.2700,
lng: -89.3700,
website: "https://www.getducks.com/ushunts/louisiana-duck-hunting-coastal-marsh/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – mid Jan" },
priceStarting: 600,
priceNotes: "All-inclusive; sleeps up to 20",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Hunts over 10 square miles of premium exclusive coastal marsh leases south of New Orleans.",
highlights: ["10 sq miles exclusive marsh leases", "3 steps from lodge to blind", "Trophy canvasbacks in January"],
tags: ["Featured", "Verified"]
},

{
id: "pecan-island-west-hunt-club-la",
name: "Pecan Island West Hunt Club",
verified: true,
city: "Pecan Island",
state: "LA",
stateFull: "Louisiana",
lat: 29.6541,
lng: -92.4543,
website: "https://www.piwesthunting.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept 20 – Sept 28", duck: "Nov 15 – Jan 25" },
priceStarting: 350,
priceNotes: "1,000+ acres private water-controlled marsh",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Over 60 years of duck hunting on 1,000+ acres of private, water-controlled marsh adjacent to White Lake.",
highlights: ["60+ years hunting same property", "1,000+ acres water-controlled marsh", "Adjacent to White Lake"],
tags: ["Verified"]
},

{
id: "southern-delta-outfitters-la",
name: "Southern Delta Outfitters",
verified: true,
city: "Southwest Louisiana",
state: "LA",
stateFull: "Louisiana",
lat: 30.2266,
lng: -93.2174,
website: "https://southerndeltaoutfitter.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 375,
priceNotes: "8 pit blinds scouted daily",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Founded in 2019 with a focus on five-star guided waterfowl experiences in Southwest Louisiana.",
highlights: ["8 scouted pit blinds", "Daily scouting for optimal placement", "Duck and goose hunting"],
tags: ["Verified"]
},

{
id: "shellshocked-guide-service-la",
name: "Shellshocked Guide Service",
verified: true,
city: "Central Louisiana",
state: "LA",
stateFull: "Louisiana",
lat: 31.2448,
lng: -92.4451,
website: "https://shellshockedguide.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – Jan" },
priceStarting: 450,
priceNotes: "All-inclusive corporate packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Licensed and insured Central Louisiana waterfowl outfitter hunting Louisiana Delta Plantation.",
highlights: ["Louisiana Delta Plantation access", "Catahoula Lake hunting", "Corporate all-inclusive packages"],
tags: ["Verified"]
},

{
id: "level-7-outdoors-la",
name: "Level 7 Outdoors",
verified: true,
city: "Catahoula Lake",
state: "LA",
stateFull: "Louisiana",
lat: 31.5000,
lng: -92.0000,
website: "https://level7outdoors.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – Jan" },
priceStarting: 350,
priceNotes: "Hunt Only or Hunt & Lodging packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–10 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Waterfront lodge on Larto Lake — part of the nearly 8,000-acre Saline/Larto complex.",
highlights: ["1,000+ decoy spreads", "Waterfront lodge on Larto Lake", "Airport pickup included"],
tags: ["Verified"]
},

{
id: "cajun-fishing-adventures-la",
name: "Cajun Fishing Adventures",
verified: true,
city: "Buras",
state: "LA",
stateFull: "Louisiana",
lat: 29.3600,
lng: -89.5300,
website: "https://www.cajunfishingadventures.com/",
phone: "(985) 785-9833",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan" },
priceStarting: 450,
priceNotes: "All-inclusive duck hunt + fishing combos",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–4 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Voted Top 5 fishing lodge in North America by Sportfishing Magazine. Hunting in Mississippi River Delta.",
highlights: ["Top 5 fishing lodge in North America", "Mississippi River Delta location", "Hunt + fishing all-inclusive combos"],
tags: ["Verified"]
},

{
id: "johnny-wink-megabucks-la",
name: "Johnny Wink's Megabucks Duck Guides",
verified: true,
city: "Natchitoches",
state: "LA",
stateFull: "Louisiana",
lat: 31.7607,
lng: -93.0863,
website: "https://johnnywink.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan (60 days)" },
priceStarting: 350,
priceNotes: "45 years guiding; fully booked each season",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Johnny Wink has guided duck hunts in Louisiana for 45 years. Stays fully booked every season.",
highlights: ["45 years guiding", "Fully booked every season", "International repeat clientele"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — MISSOURI
// ════════════════════════════════════════

{
id: "treasure-island-outfitters-mo",
name: "Treasure Island Outfitters",
verified: true,
city: "Southeast Missouri Bootheel",
state: "MO",
stateFull: "Missouri",
lat: 36.1500,
lng: -89.8000,
website: "https://treasureislandducks.com/",
phone: "(731) 487-3958",
email: "marshall@treasureislandducks.com",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { duck: "Late Nov – late Jan", goose: "Nov – Jan", snowGoose: "Jan – Feb" },
priceStarting: 300,
priceNotes: "Guided $300/person/day; All-inclusive $1,500/person for 3 days",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Southeast Missouri bootheel outfitter bordering Big Lake National Wildlife Refuge.",
highlights: ["Borders Big Lake NWR", "9,000 sq ft lodge — 12 private rooms", "Guided, all-inclusive, and DIY options"],
tags: ["Featured", "Verified"]
},

{
id: "rogers-goosedown-outfitters-mo",
name: "Rogers Goosedown Outfitters",
verified: true,
city: "Kennett",
state: "MO",
stateFull: "Missouri",
lat: 36.2362,
lng: -90.0521,
website: "https://rogersgoosedownoutfitters.com/",
phone: "(636) 698-3526",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan", snowGoose: "Spring conservation season" },
priceStarting: 225,
priceNotes: "$225/person per morning hunt; most affordable guided option",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Based in Kennett in the Missouri bootheel — known as 'waterfowl country.'",
highlights: ["$225/person per morning — most affordable", "150+ decoy spreads pre-set", "Dry pit blinds"],
tags: ["Verified"]
},

{
id: "fowl-lifestyle-outfitters-mo",
name: "Fowl Lifestyle Outfitters",
verified: true,
city: "Rives",
state: "MO",
stateFull: "Missouri",
lat: 36.2500,
lng: -89.9500,
website: "https://www.fowllifestyleoutfitters.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 300,
priceNotes: "Guided and daily pit lease options",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: true,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Southeast Missouri outfitter hunting over 500 to 3,000+ decoy spreads.",
highlights: ["500–3,000 decoy spreads", "Big Lake NWR proximity", "Five-star Elk Chute Lodge nearby"],
tags: ["Verified"]
},

{
id: "js-migrators-guide-service-mo",
name: "J&S Migrators Guide Service",
verified: true,
city: "Southeast Missouri",
state: "MO",
stateFull: "Missouri",
lat: 36.5000,
lng: -89.7000,
website: "https://duckhuntingguideservice.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan (specklebelly)", snowGoose: "Spring conservation season" },
priceStarting: 300,
priceNotes: "30+ years experience",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Over 30 years of guiding five-star waterfowl hunts in Southeast Missouri.",
highlights: ["30+ years guiding experience", "Exclusive access to prime SEMO fields", "Specklebelly and snow goose hunts"],
tags: ["Verified"]
},

{
id: "prairie-marsh-farm-mo",
name: "Prairie Marsh Farm",
verified: true,
city: "St. Charles County",
state: "MO",
stateFull: "Missouri",
lat: 38.8000,
lng: -90.7000,
website: "https://prairiemarshfarm.com/",
phone: "(636) 240-9426",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan (through the freeze)", goose: "Nov – Jan" },
priceStarting: 350,
priceNotes: "30 minutes from St. Louis",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Located just 30 minutes from St. Louis on the Mississippi Flyway.",
highlights: ["30 minutes from St. Louis", "Hunts through the freeze — late season", "Lodge sleeps 20 with private bathrooms"],
tags: ["Featured", "Verified"]
},

{
id: "habitat-flats-mo",
name: "Habitat Flats",
verified: true,
city: "Missouri",
state: "MO",
stateFull: "Missouri",
lat: 39.0000,
lng: -92.5000,
website: "https://www.habitatflats.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 600,
priceNotes: "All-inclusive; 5-star meals and lodge",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Recognized as North America's #1 waterfowl lodge network since 2008.",
highlights: ["North America's #1 waterfowl network", "Five-star meals and luxury lodging", "Canada (Saskatchewan) also available"],
tags: ["Featured", "Verified"]
},

{
id: "springville-creek-outfitters-mo",
name: "Springville Creek Outfitters",
verified: true,
city: "Missouri Bootheel",
state: "MO",
stateFull: "Missouri",
lat: 36.3000,
lng: -89.8000,
website: "https://www.springvillecreekoutfitters.com/",
phone: "(731) 697-3563",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan", snowGoose: "Spring conservation season" },
priceStarting: 275,
priceNotes: "Family-run 40+ years",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Family-run Missouri bootheel waterfowl outfitter in business for over 40 years.",
highlights: ["Family-run 40+ years", "Beginners and experts welcome", "Duck, goose, and snow goose"],
tags: ["Verified"]
}

];

// Export for use in site
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { OUTFITTERS };
}

// Make globally available (browser only)
if (typeof window !== 'undefined') {
  window.OUTFITTERS = OUTFITTERS;
}