// outfitters.js
// HuntGuideHub — Verified Outfitter Data
// Last updated: April 2026
// All websites confirmed active at time of research.

const OUTFITTERS = [

  // ── ELK — COLORADO ─────────────────────────────────────────

  {
    id: "elk-basin-outfitters-co",
    name: "Elk Basin Outfitters",
    verified: true,
    city: "Paonia",
    state: "CO",
    stateFull: "Colorado",
    lat: 38.8681,
    lng: -107.5942,
    website: "https://elkbasinoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept 1 – Sept 30", rifle: "Oct – Nov" },
    priceStarting: 3500,
    priceNotes: "5–7 day guided elk hunt",
    lodging: "Tent Camp",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.8,
    description: "The only licensed outfitter in the West Elk Basin, operating under USDA Forest Service permit on the Grand Mesa, Uncompahgre, and Gunnison National Forests. Owner Bill Allen has over 40 years of experience guiding Colorado elk hunts.",
    highlights: ["Only licensed outfitter in West Elk Basin", "40+ years experience", "Archery and rifle hunts"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "colorado-elk-outfitter-co",
    name: "Colorado Elk Outfitter",
    verified: true,
    city: "Colorado Springs",
    state: "CO",
    stateFull: "Colorado",
    lat: 38.8339,
    lng: -104.8214,
    website: "https://coloradoelkoutfitter.com/",
    phone: "",
    email: "info@coloradoelkoutfitter.com",
    image: "",
    species: ["Elk"],
    methods: ["Rifle", "Archery", "Muzzleloader"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept 1 – Sept 30", rifle: "Oct 12 – Nov 20", muzzleloader: "Sept 14 – Sept 22" },
    priceStarting: 2500,
    priceNotes: "5-day guided rifle hunt",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "75%",
    landType: "Private",
    rating: 4.7,
    description: "Licensed Colorado elk outfitter offering archery, rifle, and muzzleloader hunts near Colorado Springs. Expert guides with deep local knowledge of Colorado's largest elk herds.",
    highlights: ["Archery, rifle, muzzleloader", "75% success rate", "Private land access"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "gunnison-country-outfitters-co",
    name: "Gunnison Country Outfitters",
    verified: true,
    city: "Gunnison",
    state: "CO",
    stateFull: "Colorado",
    lat: 38.5458,
    lng: -106.9247,
    website: "https://gunnisoncountryoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov" },
    priceStarting: 3500,
    priceNotes: "Gunnison Basin world-class elk country",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.7,
    description: "Gunnison-area Colorado outfitter with access to some of the state's best elk country. The Gunnison Basin is famous for producing trophy bulls and healthy deer herds.",
    highlights: ["Gunnison Basin elk", "Trophy bulls", "World-class elk country"],
    tags: ["Verified"]
  },

  {
    id: "colorado-big-game-outfitters-co",
    name: "Colorado Big Game Outfitters",
    verified: true,
    city: "Durango",
    state: "CO",
    stateFull: "Colorado",
    lat: 37.2753,
    lng: -107.8801,
    website: "https://coloradobiggameoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Bear"],
    methods: ["Rifle", "Archery", "Muzzleloader"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov" },
    priceStarting: 3500,
    priceNotes: "Southwest Colorado near Durango",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.6,
    description: "Southwest Colorado big game outfitter based near Durango with access to quality elk, mule deer, and bear hunting in the San Juan Mountains.",
    highlights: ["San Juan Mountains", "Elk mule deer bear", "Southwest Colorado"],
    tags: ["Verified"]
  },

  // ── ELK — WYOMING ──────────────────────────────────────────

  {
    id: "timberline-outfitters-wy",
    name: "Timberline Outfitters",
    verified: true,
    city: "Cheyenne",
    state: "WY",
    stateFull: "Wyoming",
    lat: 41.1400,
    lng: -104.8202,
    website: "https://www.timberlinehunting.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Antelope", "Bear", "Turkey"],
    methods: ["Rifle", "Archery", "Muzzleloader"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
    priceStarting: 4500,
    priceNotes: "5-day guided elk hunt",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.7,
    description: "Wyoming outfitter with 40+ years guiding big game hunts for elk, mule deer, pronghorn antelope, black bear, and Merriam's turkey across Wyoming, Colorado, and Iowa.",
    highlights: ["40+ years in operation", "Multiple species available", "Archery and rifle hunts"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "table-mountain-outfitters-wy",
    name: "Table Mountain Outfitters",
    verified: true,
    city: "Cody",
    state: "WY",
    stateFull: "Wyoming",
    lat: 44.5261,
    lng: -109.0576,
    website: "https://www.tablemountainoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Antelope", "Bear", "Whitetail Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov" },
    priceStarting: 4500,
    priceNotes: "5-day guided elk hunt",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.7,
    description: "Premier Wyoming outfitter specializing in trophy class guided hunts for elk, antelope, mule deer, whitetail deer, and black bear. Spring Idaho black bear hunts with hound hunting also offered.",
    highlights: ["Multiple Wyoming species", "Idaho spring bear hunts", "Trophy class operations"],
    tags: ["Verified"]
  },

  {
    id: "sns-outfitter-guides-wy",
    name: "SNS Outfitter and Guides",
    verified: true,
    city: "Casper",
    state: "WY",
    stateFull: "Wyoming",
    lat: 42.8666,
    lng: -106.3130,
    website: "https://www.huntwyo.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Antelope", "Whitetail Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
    priceStarting: 3500,
    priceNotes: "5-day guided elk hunt; combo mule deer and antelope available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "95–100%",
    landType: "Both",
    rating: 4.8,
    description: "Operates on Bridger-Teton National Forest, Thunder Basin National Grasslands, and Bureau of Land Management land. Known for combo mule deer and antelope hunts with a 95–100% success rate.",
    highlights: ["95–100% success rate on combo hunts", "BLM and National Forest permits", "Montana mule deer available"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "big-horn-outfitters-wy",
    name: "Big Horn Outfitters",
    verified: true,
    city: "Lander",
    state: "WY",
    stateFull: "Wyoming",
    lat: 42.5494,
    lng: -108.8546,
    website: "https://www.bighornoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov" },
    priceStarting: 2700,
    priceNotes: "5-day guided Wyoming elk hunt",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.6,
    description: "Wyoming outfitter based in Lander offering guided elk and mule deer hunts in Wind River country.",
    highlights: ["Wind River country", "Elk and mule deer", "Public and private land"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "tyler-sims-outfitting-wy",
    name: "Tyler Sims Outfitting",
    verified: true,
    city: "McFadden",
    state: "WY",
    stateFull: "Wyoming",
    lat: 41.8025,
    lng: -106.1817,
    website: "https://www.tylersims.com/",
    phone: "(307) 378-2400",
    email: "",
    image: "",
    species: ["Antelope", "Mule Deer", "Elk"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { antelope: "Aug – Sept", muledeer: "Oct", elk: "Sept – Nov" },
    priceStarting: 2500,
    priceNotes: "Antelope hunts; elk and mule deer priced separately",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–5 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Operates on 250,000 acres of private land in southeastern Wyoming. Specializes in pronghorn antelope, mule deer, and elk. Permitted on Medicine Bow-Routt National Forest.",
    highlights: ["250,000 acres private land", "High antelope numbers", "NF permit holder"],
    tags: ["Verified"]
  },

  {
    id: "thomson-outfitters-wy",
    name: "Thomson Outfitters",
    verified: true,
    city: "Pinedale",
    state: "WY",
    stateFull: "Wyoming",
    lat: 42.8677,
    lng: -109.8609,
    website: "https://www.wyohunt.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Antelope"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct", antelope: "Aug – Oct" },
    priceStarting: 4000,
    priceNotes: "5-day guided hunt; includes meals, lodging, guides, horses",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.6,
    description: "Guides the Bridger-Teton National Forest, home to the largest mule deer migration in western Wyoming. Offers horse-backed elk and deer hunts.",
    highlights: ["Largest mule deer migration in western WY", "Horse-backed hunts available", "Bridger-Teton National Forest"],
    tags: ["Verified"]
  },

  {
    id: "diamond-4-ranch-wy",
    name: "Allen's Diamond 4 Ranch",
    verified: true,
    city: "Lander",
    state: "WY",
    stateFull: "Wyoming",
    lat: 42.8330,
    lng: -108.7307,
    website: "https://diamond4ranch.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Antelope", "Moose"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
    priceStarting: 4000,
    priceNotes: "Varies by species; all inclusive",
    lodging: "Ranch",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.7,
    description: "Family-owned Wyoming outfitter licensed since 1973 — 5th generation Wyoming family. Guides wilderness and public land in western Wyoming for elk, mule deer, pronghorn antelope, and moose.",
    highlights: ["Licensed since 1973", "5th generation Wyoming family", "Wilderness and public land hunting"],
    tags: ["Verified"]
  },

  {
    id: "thunder-ridge-outfitters-wy",
    name: "Thunder Ridge Outfitters",
    verified: true,
    city: "Dubois",
    state: "WY",
    stateFull: "Wyoming",
    lat: 43.5333,
    lng: -109.6292,
    website: "https://thunderridgeoutfitter.com/",
    phone: "(307) 439-3302",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer", "Antelope", "Moose"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided", "Drop Camp"],
    seasons: { archery: "Sept", rifle: "Oct – Nov" },
    priceStarting: 3500,
    priceNotes: "Guided hunts; drop camp also available",
    lodging: "Tent Camp",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.6,
    description: "Family-owned Wyoming outfitter in business since 1982, now in 5th generation. Trophy class guided hunts for elk, mule deer, pronghorn antelope, mountain lion, and moose. Drop camps also available.",
    highlights: ["In business since 1982", "5th generation outfitter", "Drop camps available"],
    tags: ["Verified"]
  },

  // ── ELK — ARIZONA ──────────────────────────────────────────

  {
    id: "arizona-elk-hunts-az",
    name: "Arizona Elk Hunts",
    verified: true,
    city: "Flagstaff",
    state: "AZ",
    stateFull: "Arizona",
    lat: 35.1983,
    lng: -111.6513,
    website: "https://arizonaelkhunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk"],
    methods: ["Rifle", "Archery", "Muzzleloader"],
    tripTypes: ["Guided"],
    seasons: { archery: "Aug – Sept", rifle: "Oct – Nov" },
    priceStarting: 5000,
    priceNotes: "Arizona draw tags required; bonus point system",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.7,
    description: "Arizona elk hunting outfitter based in Flagstaff. Arizona is nearly all draw-only for elk with a bonus point system. Outfitter provides full draw tag guidance.",
    highlights: ["Trophy Arizona elk", "Draw tag guidance provided", "Flagstaff area"],
    tags: ["Verified"]
  },

  // ── ELK — IDAHO ────────────────────────────────────────────

  {
    id: "mile-high-outfitters-id",
    name: "Mile High Outfitters of Idaho",
    verified: true,
    city: "McCall",
    state: "ID",
    stateFull: "Idaho",
    lat: 44.9044,
    lng: -116.1003,
    website: "https://www.milehighoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Bear", "Cougar"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided", "Drop Camp"],
    seasons: { archery: "Aug 29 – Sept 29", rifle: "Oct – Nov" },
    priceStarting: 6500,
    priceNotes: "1:1 $8,000; 2:1 $6,500; drop camps $2,500/person",
    lodging: "Tent Camp",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "7–9 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.8,
    description: "Licensed by Idaho Outfitters and Guides Licensing Board. Operates in Frank Church Wilderness Area on Payette National Forest. Member of Idaho Outfitters and Guides Association since 1995. Fair chase only.",
    highlights: ["Frank Church Wilderness", "Licensed since 1995", "Drop camps available", "Fair chase only"],
    tags: ["Verified"]
  },

  // ── ELK — MONTANA ──────────────────────────────────────────

  {
    id: "yellowstone-trophy-hunts-mt",
    name: "Yellowstone Trophy Hunts",
    verified: true,
    city: "West Yellowstone",
    state: "MT",
    stateFull: "Montana",
    lat: 44.6602,
    lng: -111.0990,
    website: "https://ythunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Mule Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Sept", rifle: "Oct – Nov" },
    priceStarting: 4500,
    priceNotes: "Trophy class elk near Yellowstone",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.6,
    description: "Trophy elk and mule deer hunting near Yellowstone in West Montana. Exclusive access to prime habitat in one of the most productive elk regions in North America.",
    highlights: ["Near Yellowstone", "Trophy class elk", "Prime Montana habitat"],
    tags: ["Verified"]
  },

  // ── HOG — TEXAS ────────────────────────────────────────────

  {
    id: "white-oak-outfitters-tx",
    name: "White Oak Outfitters",
    verified: true,
    city: "Northeast Texas",
    state: "TX",
    stateFull: "Texas",
    lat: 33.4260,
    lng: -95.5750,
    website: "https://www.texashoghuntingoutfitters.com/",
    phone: "(903) 466-1358",
    email: "",
    image: "",
    species: ["Hog", "Whitetail Deer"],
    methods: ["Rifle", "Archery", "Thermal/Night"],
    tripTypes: ["Guided"],
    seasons: { hog: "Year-round" },
    priceStarting: 700,
    priceNotes: "2-day 2-night all-inclusive hog hunt; no hidden fees",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: false,
    tripLength: "2 days",
    groupSize: "1–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Owner Bruce Hunnicutt has over 30 years guiding hog hunts in Northeast Texas. No hunting license required for hogs. All-inclusive packages with climate-controlled lodge, 44 timed feeders, and hog cleaning included.",
    highlights: ["30+ years experience", "No license required for hogs", "Hog cleaning included", "No hidden fees"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "texas-thermal-outfitters-tx",
    name: "Texas Thermal Outfitters",
    verified: true,
    city: "Graham",
    state: "TX",
    stateFull: "Texas",
    lat: 33.1068,
    lng: -98.5895,
    website: "https://texasthermaloutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Hog", "Whitetail Deer", "Turkey"],
    methods: ["Rifle", "Thermal/Night", "Spot & Stalk"],
    tripTypes: ["Guided"],
    seasons: { hog: "Year-round" },
    priceStarting: 395,
    priceNotes: "1-night $395; 2-night $770; 3-night $1,125",
    lodging: "Lodge",
    lodgingIncluded: false,
    mealsIncluded: false,
    tripLength: "1–3 nights",
    groupSize: "1–6 hunters",
    successRate: "100%",
    landType: "Private",
    rating: 4.8,
    description: "Specializes in thermal night hog hunts using state-of-the-art thermal scopes and cell cameras on all feeders. 100% opportunity rate since May 2023.",
    highlights: ["100% opportunity rate", "Thermal scopes provided", "No hog limit", "Real-time cell cameras"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "first-shot-outfitters-tx",
    name: "First Shot Outfitters",
    verified: true,
    city: "Coleman",
    state: "TX",
    stateFull: "Texas",
    lat: 31.8288,
    lng: -99.3101,
    website: "https://firstshothunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Hog", "Whitetail Deer", "Turkey"],
    methods: ["Rifle", "Archery", "Thermal/Night", "Spot & Stalk"],
    tripTypes: ["Guided"],
    seasons: { hog: "Year-round" },
    priceStarting: 1875,
    priceNotes: "2 days hunting / 3 nights lodging; thermal night hunt $2,275",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–3 days",
    groupSize: "1–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Controls over 600,000 acres in Central Texas. Unlimited hog harvest. Home-cooked meals. Located near Austin, Dallas, Fort Worth, and Houston.",
    highlights: ["600,000+ acres", "Unlimited hog harvest", "Thermal night hunts available", "Home-cooked meals"],
    tags: ["Verified"]
  },

  {
    id: "cavender-whitetail-hunts-tx",
    name: "Cavender Whitetail Hunts",
    verified: true,
    city: "Eastland",
    state: "TX",
    stateFull: "Texas",
    lat: 32.4015,
    lng: -98.8206,
    website: "https://www.cavenderwhitetailhunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Whitetail Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { deer: "Nov – Jan" },
    priceStarting: 2600,
    priceNotes: "Trophy whitetail packages; all-inclusive",
    lodging: "Ranch",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–5 days",
    groupSize: "1–8 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.5,
    description: "Texas whitetail outfitter in Eastland County specializing in trophy whitetail deer on private Texas ranch land.",
    highlights: ["Trophy whitetail", "Private Texas ranch", "All-inclusive"],
    tags: ["Featured", "Verified"]
  },

  // ── PHEASANT — SOUTH DAKOTA ─────────────────────────────────

  {
    id: "northern-plains-outfitters-sd",
    name: "Northern Plains Outfitters",
    verified: true,
    city: "Athol",
    state: "SD",
    stateFull: "South Dakota",
    lat: 45.0245,
    lng: -98.5903,
    website: "https://northernplainsoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Pheasant", "Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { pheasant: "Oct – Jan", waterfowl: "Sept – Jan", snowGoose: "Feb – March" },
    priceStarting: 1800,
    priceNotes: "All-inclusive packages; private lodging per group",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–5 days",
    groupSize: "2–16 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Full-service hunting operation in business for 25 years near Aberdeen, South Dakota. Hunts over 25,000 acres of professionally managed habitat. Private lodging — your group never shares space with other hunters.",
    highlights: ["25 years in operation", "25,000+ acres", "Private lodging per group", "Snow goose hunts available"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "eagle-pass-lodge-sd",
    name: "Eagle Pass Lodge",
    verified: true,
    city: "Pierre",
    state: "SD",
    stateFull: "South Dakota",
    lat: 44.3683,
    lng: -100.3510,
    website: "https://www.eaglepasslodge.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Pheasant"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { pheasant: "Oct – Jan" },
    priceStarting: 3500,
    priceNotes: "Luxury all-inclusive packages",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–5 days",
    groupSize: "4–20 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Luxury South Dakota pheasant hunting on 12,000 acres with a 15,000 sq ft lodge featuring movie theater, spa, par 3 golf course, tennis court, five-stand sporting clays, and bass pond.",
    highlights: ["12,000 acres", "Luxury lodge with spa and theater", "Sporting clays course", "History since 1920"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "coteau-view-hunts-sd",
    name: "Coteau View Hunts",
    verified: true,
    city: "Conde",
    state: "SD",
    stateFull: "South Dakota",
    lat: 45.1597,
    lng: -98.0936,
    website: "https://coteauviewhunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Pheasant"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { pheasant: "Oct – Jan" },
    priceStarting: 1500,
    priceNotes: "All-inclusive packages available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–4 days",
    groupSize: "4–14 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Premier South Dakota pheasant hunting lodge on 12,000+ acres in Northeastern South Dakota near Conde. 90%+ rebooking rate. Wild pheasants only.",
    highlights: ["12,000+ acres", "90%+ rebooking rate", "Wild pheasants only"],
    tags: ["Verified"]
  },

  {
    id: "wagon-wheel-ranch-sd",
    name: "Wagon Wheel Ranch",
    verified: true,
    city: "Kimball",
    state: "SD",
    stateFull: "South Dakota",
    lat: 43.7455,
    lng: -98.9603,
    website: "https://www.dakota-pheasant-hunting.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Pheasant"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { pheasant: "Oct – Jan" },
    priceStarting: 1995,
    priceNotes: "2-5 day packages starting at $1,995 all-inclusive",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–5 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Located near Kimball in south central South Dakota. Over 5,300 acres of prime hunting land. In operation for over 25 years. Walleye fishing combo packages available.",
    highlights: ["25+ years in operation", "5,300+ acres", "Fishing combos available"],
    tags: ["Verified"]
  },

  {
    id: "dakota-prairie-lodge-sd",
    name: "Dakota Prairie Lodge",
    verified: true,
    city: "South Dakota",
    state: "SD",
    stateFull: "South Dakota",
    lat: 44.5000,
    lng: -99.5000,
    website: "https://sd-pheasanthunting.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Pheasant", "Waterfowl", "Dove"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { pheasant: "Oct – Jan", dove: "Sept" },
    priceStarting: 2000,
    priceNotes: "All-inclusive; unlimited shells; 3 wild roosters/day cleaned",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–4 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Wild pheasant hunting only — no pen-raised birds. All-inclusive with unlimited shells, 3 wild roosters per day cleaned and vacuum-packed. Dog-friendly with kennels on site.",
    highlights: ["Wild birds only", "Unlimited shells included", "Dog-friendly with kennels"],
    tags: ["Verified"]
  },

  // ── WATERFOWL — ARKANSAS ────────────────────────────────────

  {
    id: "falling-feather-outdoors-ar",
    name: "Falling Feather Outdoors",
    verified: true,
    city: "Delaplaine",
    state: "AR",
    stateFull: "Arkansas",
    lat: 36.2667,
    lng: -90.7667,
    website: "https://fallingfeatheroutdoors.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
    priceStarting: 400,
    priceNotes: "Per hunter per day; private lodge for your group only; minimum 4 hunters",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: false,
    tripLength: "2–4 days",
    groupSize: "4–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Located in the delta of Northeast Arkansas on 2,500+ acres of rice, soybeans, and corn. Private lodge exclusively for your group. Guide team has 40+ combined years of experience.",
    highlights: ["2,500+ acres prime delta", "Private lodge — your group only", "40+ years guide experience"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "leg-iron-outfitters-ar",
    name: "Leg Iron Outfitters and Lodging",
    verified: true,
    city: "Biggers",
    state: "AR",
    stateFull: "Arkansas",
    lat: 36.3833,
    lng: -90.6167,
    website: "https://legironoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – March" },
    priceStarting: 450,
    priceNotes: "Per hunter per day; 64 private rooms available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: false,
    tripLength: "2–5 days",
    groupSize: "2–64 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "44,500+ acres of rice, corn, soybean fields, and private green timber in Biggers, Arkansas. Two massive lodges totaling 52,000 sq ft with 64 private rooms. Spring conservation snow goose hunts also available.",
    highlights: ["44,500+ acres", "64 private rooms", "Mississippi Flyway", "Snow goose season also"],
    tags: ["Verified"]
  },

  {
    id: "cupped-wings-guide-ar",
    name: "Cupped Wings Guide Service",
    verified: true,
    city: "Northeast Arkansas",
    state: "AR",
    stateFull: "Arkansas",
    lat: 35.5000,
    lng: -90.5000,
    website: "https://www.cuppedwingsguideservice.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided", "Self-Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – March" },
    priceStarting: 400,
    priceNotes: "Guided and self-guided options; pit blind leases $750/day for 6 hunters",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–5 days",
    groupSize: "2–20 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Arkansas premier duck and waterfowl outfitter operating since 1999 from two lodges. Self-guided pit blind leases also available. Family-friendly.",
    highlights: ["Operating since 1999", "Two lodge locations", "Self-guided leases available"],
    tags: ["Verified"]
  },

  {
    id: "bayou-bottoms-ar",
    name: "Bayou Bottoms Guide Service",
    verified: true,
    city: "Fisher",
    state: "AR",
    stateFull: "Arkansas",
    lat: 35.9000,
    lng: -91.1500,
    website: "https://www.bayoubottoms.com/",
    phone: "(618) 889-0919",
    email: "mcneal30@hotmail.com",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
    priceStarting: 350,
    priceNotes: "Competitive rates; call directly to book",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: false,
    tripLength: "2–4 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Over 20 years operating in Northeast Arkansas on 2,500+ acres. Small groups preferred. Guides scout from 2pm to dark every afternoon.",
    highlights: ["20+ years operating", "2,500+ prime acres", "Small groups for better hunts"],
    tags: ["Verified"]
  },

  // ── WATERFOWL — LOUISIANA ───────────────────────────────────

  {
    id: "limitless-waterfowl-la",
    name: "Limitless Waterfowl Outfitters",
    verified: true,
    city: "Venice",
    state: "LA",
    stateFull: "Louisiana",
    lat: 29.2741,
    lng: -89.3484,
    website: "https://limitless-waterfowl.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { teal: "Sept", duck: "Nov – Jan", goose: "Nov – Jan" },
    priceStarting: 400,
    priceNotes: "Per hunter per day; lodging, meals, and fishing combos available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "1–5 days",
    groupSize: "2–20 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Established 2013. Owned by 6th generation Venice native Captain Kevin Drury Jr. Southern tip of the Mississippi Flyway. 15+ duck species in a single hunt possible.",
    highlights: ["6th generation Venice native guide", "Southern tip of Mississippi Flyway", "15+ duck species", "Hunt/fish combo packages"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "saltgrass-lodge-la",
    name: "Saltgrass Lodge",
    verified: true,
    city: "Venice",
    state: "LA",
    stateFull: "Louisiana",
    lat: 29.2800,
    lng: -89.3600,
    website: "https://saltgrassoutdoors.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl", "Hog"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", teal: "Sept" },
    priceStarting: 500,
    priceNotes: "All-inclusive; Blast and Cast duck and fishing combos available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "1–4 days",
    groupSize: "2–20 hunters",
    successRate: "90%+",
    landType: "Private",
    rating: 4.9,
    description: "Nearly 7,000 sq ft antebellum-style lodge overlooking the Mississippi River in Venice. 90%+ limit rates. Gourmet Cajun chef on site. Blast and Cast packages combine morning duck hunts with afternoon redfish fishing.",
    highlights: ["90%+ limit rates", "7,000 sq ft luxury lodge", "Gourmet Cajun chef", "Blast and Cast combos"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "johnny-wink-megabucks-la",
    name: "Johnny Wink's Megabucks Duck Guides",
    verified: true,
    city: "Natchitoches",
    state: "LA",
    stateFull: "Louisiana",
    lat: 31.7607,
    lng: -93.0863,
    website: "https://johnnywink.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan" },
    priceStarting: 350,
    priceNotes: "45 years guiding; fully booked each season — book early",
    lodging: "Lodge",
    lodgingIncluded: false,
    mealsIncluded: false,
    tripLength: "1–3 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Johnny Wink has guided duck hunts in Louisiana for 45 years. Stays fully booked every season. Hunters have traveled from Scotland, Canada, Jamaica, and South Africa to hunt with Johnny.",
    highlights: ["45 years guiding", "Fully booked every season — book early", "International repeat clientele"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "cajun-fishing-adventures-la",
    name: "Cajun Fishing Adventures",
    verified: true,
    city: "Buras",
    state: "LA",
    stateFull: "Louisiana",
    lat: 29.3600,
    lng: -89.5300,
    website: "https://www.cajunfishingadventures.com/",
    phone: "(985) 785-9833",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan" },
    priceStarting: 450,
    priceNotes: "All-inclusive duck hunt and fishing combos; Top 5 fishing lodge in North America",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–4 days",
    groupSize: "2–20 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "One hour from New Orleans in Buras. Voted Top 5 fishing lodge in North America by Sportfishing Magazine. Mississippi River Delta hunting grounds.",
    highlights: ["Top 5 fishing lodge in North America", "1 hour from New Orleans", "Hunt and fishing combos"],
    tags: ["Verified"]
  },

  // ── WATERFOWL — MISSOURI ────────────────────────────────────

  {
    id: "treasure-island-outfitters-mo",
    name: "Treasure Island Outfitters",
    verified: true,
    city: "Southeast Missouri Bootheel",
    state: "MO",
    stateFull: "Missouri",
    lat: 36.1500,
    lng: -89.8000,
    website: "https://treasureislandducks.com/",
    phone: "(731) 487-3958",
    email: "marshall@treasureislandducks.com",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided", "Self-Guided"],
    seasons: { duck: "Late Nov – late Jan", goose: "Nov – Jan", snowGoose: "Jan – Feb" },
    priceStarting: 300,
    priceNotes: "Guided $300/person/day; All-inclusive $1,500/person 3 days; DIY $500/day",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "1–4 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Southeast Missouri bootheel outfitter bordering Big Lake National Wildlife Refuge. 9,000 sq ft lodge with 12 double bedrooms. Guided, all-inclusive, and DIY options.",
    highlights: ["Borders Big Lake NWR", "9,000 sq ft lodge — 12 private rooms", "Guided, all-inclusive, and DIY options"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "habitat-flats-mo",
    name: "Habitat Flats",
    verified: true,
    city: "Missouri",
    state: "MO",
    stateFull: "Missouri",
    lat: 39.0000,
    lng: -92.5000,
    website: "https://www.habitatflats.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
    priceStarting: 600,
    priceNotes: "All-inclusive; 5-star meals; also operates in Saskatchewan Canada",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–5 days",
    groupSize: "2–16 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Recognized as North America's #1 waterfowl lodge network since 2008. Five-star meals, luxury lodging, expertly guided duck and goose hunts. Also operates in Saskatchewan, Canada.",
    highlights: ["North America's #1 waterfowl network", "In operation since 2008", "Five-star meals and luxury lodging", "Canada Saskatchewan also available"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "prairie-marsh-farm-mo",
    name: "Prairie Marsh Farm",
    verified: true,
    city: "St. Charles County",
    state: "MO",
    stateFull: "Missouri",
    lat: 38.8000,
    lng: -90.7000,
    website: "https://prairiemarshfarm.com/",
    phone: "(636) 240-9426",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
    priceStarting: 350,
    priceNotes: "30 minutes from St. Louis; lodge sleeps 20",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "1–4 days",
    groupSize: "2–20 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "30 minutes from St. Louis on the Mississippi Flyway. Hunts through the freeze into late season. Lodge sleeps 20 in 5 four-man bedrooms with private bathrooms.",
    highlights: ["30 minutes from St. Louis", "Hunts through the freeze", "Lodge sleeps 20", "Mississippi Flyway"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "rogers-goosedown-outfitters-mo",
    name: "Rogers Goosedown Outfitters",
    verified: true,
    city: "Kennett",
    state: "MO",
    stateFull: "Missouri",
    lat: 36.2362,
    lng: -90.0521,
    website: "https://rogersgoosedownoutfitters.com/",
    phone: "(636) 698-3526",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided", "Self-Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – Jan", snowGoose: "Spring conservation season" },
    priceStarting: 225,
    priceNotes: "$225/person per morning hunt; most affordable guided option in SE Missouri",
    lodging: "Lodge",
    lodgingIncluded: false,
    mealsIncluded: false,
    tripLength: "1–3 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Based in Kennett in the Missouri bootheel. $225 per person per morning hunt. 150+ duck floater decoys pre-set. Dry pit blinds. Specklebelly geese and snow geese also available.",
    highlights: ["$225/person per morning — most affordable", "150+ decoy spreads pre-set", "Dry pit blinds"],
    tags: ["Verified"]
  },

  // ── TURKEY — NEBRASKA ───────────────────────────────────────

  {
    id: "heritage-outfitters-ne",
    name: "Heritage Outfitters Nebraska",
    verified: true,
    city: "Curtis",
    state: "NE",
    stateFull: "Nebraska",
    lat: 40.6333,
    lng: -100.5142,
    website: "https://heritageoutfittersne.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Turkey", "Whitetail Deer", "Mule Deer"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { turkey: "Spring and Fall; OTC tags", deer: "Oct – Jan" },
    priceStarting: 1200,
    priceNotes: "Turkey, Mule Deer, and Whitetail on 40,000+ acres private land",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–5 days",
    groupSize: "1–8 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Turkey hunts on 40,000+ acres of private western Nebraska featuring Rio Grande, Merriam's, and hybrid turkeys. OTC Nebraska tags — no draw required. Also guides mule deer and whitetail.",
    highlights: ["Rio Grande Merriam's and hybrids", "40,000+ acres private land", "OTC turkey tags — no draw", "Mule deer and whitetail also"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "gobble-n-grunt-outfitters-ne",
    name: "Gobble-N-Grunt Outfitters",
    verified: true,
    city: "Nebraska",
    state: "NE",
    stateFull: "Nebraska",
    lat: 42.0000,
    lng: -100.5000,
    website: "https://huntthenorth.com/neturkey/",
    phone: "",
    email: "chris@gobblengrunt.com",
    image: "",
    species: ["Turkey"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { turkey: "Spring Merriam's" },
    priceStarting: 1000,
    priceNotes: "2-3 day spring Merriam's; guaranteed opportunity; 2-bird packages available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–3 days",
    groupSize: "2–8 hunters",
    successRate: "100%",
    landType: "Private",
    rating: 4.9,
    description: "20+ years guiding on 150,000 acres across three turkey camps. More Merriam's turkey harvested here than any other camp in the US. Guaranteed opportunity on every hunt.",
    highlights: ["20+ years guiding", "150,000 acres across 3 camps", "Most Merriam's harvested in the US", "Guaranteed opportunity"],
    tags: ["Featured", "Verified"]
  },

  // ── TURKEY — OKLAHOMA ───────────────────────────────────────

  {
    id: "western-oklahoma-trophy-outfitters",
    name: "Western Oklahoma Trophy Outfitters",
    verified: true,
    city: "Southwest Oklahoma",
    state: "OK",
    stateFull: "Oklahoma",
    lat: 34.6036,
    lng: -98.3959,
    website: "https://www.wotohunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Turkey", "Whitetail Deer", "Elk", "Hog"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided", "Semi-Guided"],
    seasons: { turkey: "Spring Rio Grande April – May", deer: "Oct – Jan", elk: "Sept – Nov", hog: "Year-round" },
    priceStarting: 1500,
    priceNotes: "40,000+ acres; two lodges in SW and south central Oklahoma",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–6 days",
    groupSize: "1–8 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Premier SW Oklahoma outfitter with 40,000+ acres managed by staff and a wildlife biologist. Rio Grande turkey, trophy whitetail, elk, and hog. Two lodge facilities.",
    highlights: ["40,000+ acres with wildlife biologist", "Rio Grande turkey — one of Oklahoma's best", "Elk deer turkey hog all available"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "tornado-valley-outfitters-ok",
    name: "Tornado Valley Outfitters",
    verified: true,
    city: "SW Oklahoma",
    state: "OK",
    stateFull: "Oklahoma",
    lat: 34.1000,
    lng: -98.5000,
    website: "https://tornadovalleyoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl", "Turkey", "Whitetail Deer", "Hog", "Dove"],
    methods: ["Shotgun", "Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { duck: "Nov – Jan", goose: "Nov – Jan", crane: "Nov – Feb", turkey: "Spring", dove: "Sept", deer: "Oct – Jan", hog: "Year-round" },
    priceStarting: 350,
    priceNotes: "SW Oklahoma and North Texas; sandhill crane specialty",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "1–4 days",
    groupSize: "2–16 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Located in SW Oklahoma and North Texas offering duck, goose, sandhill crane, dove, deer, Rio Grande turkey, and hog. Sandhill crane is a specialty — Oklahoma has some of the best crane hunting in North America.",
    highlights: ["Sandhill crane specialty", "7+ species available", "SW Oklahoma and North Texas"],
    tags: ["Verified"]
  },

  // ── TURKEY — FLORIDA ────────────────────────────────────────

  {
    id: "seminole-prairie-safaris-fl",
    name: "Seminole Prairie Safaris",
    verified: true,
    city: "Lake Okeechobee",
    state: "FL",
    stateFull: "Florida",
    lat: 26.9342,
    lng: -80.7984,
    website: "https://floridahuntingranch.com/",
    phone: "(888) 785-9378",
    email: "seminoleprairie@gmail.com",
    image: "",
    species: ["Turkey", "Hog"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided", "Semi-Guided"],
    seasons: { turkey: "Spring South Zone March 7 – April 12; North Zone March 21 – April 26", hog: "Year-round" },
    priceStarting: 1000,
    priceNotes: "2-day all-inclusive $1,000 min group of 4; includes iguana hunting bowfishing and hog hunt",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–4 days",
    groupSize: "4–8 hunters",
    successRate: "95%",
    landType: "Private",
    rating: 4.9,
    description: "Family-run for 30+ years north of Lake Okeechobee. 95% success rate on Osceola turkey — the Florida-only Grand Slam subspecies. 20,000+ acres. Package includes iguana hunting, bowfishing, and hog hunt.",
    highlights: ["30+ years same family", "95% success rate", "Osceola — Florida-only Grand Slam species", "Iguana bowfishing and hog included"],
    tags: ["Featured", "Verified"]
  },

  // ── TURKEY — MONTANA ────────────────────────────────────────

  {
    id: "musselshell-outfitters-mt",
    name: "Musselshell Outfitters",
    verified: true,
    city: "Musselshell County",
    state: "MT",
    stateFull: "Montana",
    lat: 46.5000,
    lng: -108.2500,
    website: "https://www.musselshelloutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Turkey", "Elk", "Mule Deer", "Whitetail Deer", "Pheasant"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided", "Self-Guided"],
    seasons: { turkey: "Spring April 15 – May 31 OTC", elk: "Sept – Nov", muledeer: "Oct – Nov rut", pheasant: "Oct – Dec" },
    priceStarting: 1850,
    priceNotes: "1-bird 3-day turkey $1,850 two hunters per guide; 2-bird $2,450; 32nd year from same camp",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "32nd year in business from the same camp. NWTF Patron Corporate Life Sponsor. True Merriam's turkeys — not hybrids. OTC Montana turkey tags. Also offers world-class mule deer rut hunts, elk, and pheasant.",
    highlights: ["32nd year — same camp same area", "NWTF Patron Corporate Life Sponsor", "True Merriam's not hybrids", "OTC Montana turkey tags", "Mule deer rut hunts also"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "jj-guide-service-mt",
    name: "J and J Guide Service",
    verified: true,
    city: "Ekalaka",
    state: "MT",
    stateFull: "Montana",
    lat: 45.8883,
    lng: -104.5522,
    website: "https://www.jjguide.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Turkey", "Elk", "Mule Deer", "Whitetail Deer", "Antelope", "Waterfowl", "Pheasant"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { turkey: "Spring Merriam's", elk: "Sept – Nov", muledeer: "Oct – Nov", antelope: "Aug – Sept", waterfowl: "Oct – Jan", pheasant: "Oct – Dec" },
    priceStarting: 1500,
    priceNotes: "Lodge-based turkey from Ekalaka MT; also elk deer antelope upland and waterfowl",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–7 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Southeastern Montana outfitter offering elk, mule deer, whitetail, antelope, turkey, upland birds, and waterfowl. Seven species from one outfitter. License application assistance provided.",
    highlights: ["7 species available", "Spring Merriam's spot-and-call", "Elk mule deer antelope combo", "License application assistance"],
    tags: ["Verified"]
  },

  // ── TURKEY — NEW MEXICO ─────────────────────────────────────

  {
    id: "sierra-blanca-outfitters-nm",
    name: "Sierra Blanca Outfitters",
    verified: true,
    city: "Holman",
    state: "NM",
    stateFull: "New Mexico",
    lat: 36.0000,
    lng: -105.3000,
    website: "https://www.sierrablancaoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Turkey", "Elk", "Mule Deer"],
    methods: ["Firearm", "Archery", "Handgun"],
    tripTypes: ["Guided"],
    seasons: { turkey: "Spring April 15 – May 15 OTC; youth April 10-12", elk: "Sept – Nov", muledeer: "Oct – Nov" },
    priceStarting: 1200,
    priceNotes: "Merriam's turkey OTC tag; 2-bird limit in NM spring; elk and deer also available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–5 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.8,
    description: "Grand Slam destination — Merriam's is one of the four required Grand Slam subspecies. NM spring turkey tags are OTC with a 2-bearded-bird limit. Welcomes all hunters including youth and mobility-challenged. Home-cooked meals.",
    highlights: ["Grand Slam Merriam's specialist", "OTC New Mexico turkey tags", "2-bird spring limit", "Welcomes mobility-challenged hunters"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "triple-c-outfitters-nm",
    name: "Triple C Outfitters",
    verified: true,
    city: "Lincoln National Forest",
    state: "NM",
    stateFull: "New Mexico",
    lat: 33.0000,
    lng: -105.5000,
    website: "https://www.nmelkhunts.com/turkey/",
    phone: "(505) 506-6704",
    email: "",
    image: "",
    species: ["Turkey", "Elk", "Mule Deer"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { turkey: "Spring April 15 – May 15; Youth April 10-12", elk: "Sept – Nov", muledeer: "Oct – Nov" },
    priceStarting: 2750,
    priceNotes: "3-day 4-night all-inclusive $2,750 two hunters per guide; 1-on-1 add $750; 90% shot opportunity",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3 days 4 nights",
    groupSize: "2–6 hunters",
    successRate: "90%",
    landType: "Public",
    rating: 4.9,
    description: "All hunts in Lincoln National Forest. 90% shot opportunity on mature Merriam's gobblers over 5-year average. Roosts 4-6 gobblers each evening. OTC turkey tags. Also operates elk and mule deer hunts.",
    highlights: ["90% shot opportunity 5 year average", "Lincoln National Forest", "2-bird limit", "Roost 4-6 birds nightly", "Elk and mule deer also"],
    tags: ["Featured", "Verified"]
  },

  // ── TURKEY — KANSAS ─────────────────────────────────────────

  {
    id: "ck-outfitters-ks",
    name: "CK Outfitters",
    verified: true,
    city: "Kansas",
    state: "KS",
    stateFull: "Kansas",
    lat: 38.5000,
    lng: -98.0000,
    website: "https://www.ckoutfitters.net/",
    phone: "",
    email: "",
    image: "",
    species: ["Turkey", "Whitetail Deer"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { turkey: "April – May" },
    priceStarting: 1500,
    priceNotes: "100% success rate in 2025; free return hunt guarantee if no harvest",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–5 days",
    groupSize: "1–6 hunters",
    successRate: "100%",
    landType: "Private",
    rating: 4.9,
    description: "Kansas turkey with a bold guarantee: if you don't harvest, CK Outfitters extends your hunt at their expense or has you return free the following year. 2025 season: 36 hunters harvested 36 mature birds.",
    highlights: ["100% success rate in 2025", "Free return hunt guarantee", "36 of 36 mature birds in 2025"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "beamers-guide-service-ks",
    name: "Beamers Guide Service",
    verified: true,
    city: "Northwest Kansas",
    state: "KS",
    stateFull: "Kansas",
    lat: 39.5000,
    lng: -100.5000,
    website: "https://www.beamersguideservice.com/",
    phone: "(303) 919-3899",
    email: "",
    image: "",
    species: ["Turkey"],
    methods: ["Firearm", "Archery"],
    tripTypes: ["Guided", "Semi-Guided"],
    seasons: { turkey: "Early April – end of May" },
    priceStarting: 1000,
    priceNotes: "Rio Grande turkey; Kansas and Nebraska private land",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–5 days",
    groupSize: "1–8 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Rio Grande spring turkey hunts on thousands of acres in Northwest Kansas and South-Central Nebraska — one of the highest turkey densities in the US.",
    highlights: ["Rio Grande turkeys", "Highest turkey density in US", "Kansas and Nebraska private land"],
    tags: ["Verified"]
  },

  // ── WATERFOWL — MINNESOTA ───────────────────────────────────

  {
    id: "palisade-flats-hunt-club-mn",
    name: "Palisade Flats Hunt Club",
    verified: true,
    city: "Palisade",
    state: "MN",
    stateFull: "Minnesota",
    lat: 46.7167,
    lng: -93.5000,
    website: "https://palisadeflatshc.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { goose: "Sept – Oct", duck: "Oct – Nov", teal: "Sept" },
    priceStarting: 500,
    priceNotes: "4,000+ acres; chef-prepared meals; two lodges",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–4 days",
    groupSize: "2–16 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "2.5 hours north of Minneapolis on 4,000+ acres including flooded rice paddies and Mississippi River bottoms just north of Rice Lake NWR. Sherp, Fat Truck, Marsh Master, and heated Side-by-Sides for blind transport. Chef-prepared meals.",
    highlights: ["4,000+ acres including rice paddies", "North of Rice Lake NWR", "Sherp and Fat Truck transport", "Chef-prepared meals"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "dna-guide-service-mn",
    name: "DNA Guide Service",
    verified: true,
    city: "Big Stone Lake",
    state: "MN",
    stateFull: "Minnesota",
    lat: 45.3333,
    lng: -96.4500,
    website: "https://www.dnaguideservice.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Oct – Nov", goose: "Sept – Nov" },
    priceStarting: 400,
    priceNotes: "Mallard Point Lodge on Big Stone Lake; 40 years waterfowl hunting 30 years guiding",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "2–4 days",
    groupSize: "2–8 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "Owner-guide Darren Lang has 40+ years waterfowl experience in western Minnesota. Mallard Point Lodge on Big Stone Lake. Built his own slough from a sterile cornfield — dedicated habitat conservationist.",
    highlights: ["40 years hunting 30 years guiding", "Mallard Point Lodge on Big Stone Lake", "Habitat restoration conservationist"],
    tags: ["Featured", "Verified"]
  },

  // ── WATERFOWL — WISCONSIN ───────────────────────────────────

  {
    id: "rrr-outfitters-wi",
    name: "RRR Outfitters",
    verified: true,
    city: "Ferryville",
    state: "WI",
    stateFull: "Wisconsin",
    lat: 43.3500,
    lng: -91.0800,
    website: "https://www.rrroutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl", "Turkey", "Whitetail Deer"],
    methods: ["Shotgun", "Firearm", "Archery"],
    tripTypes: ["Guided"],
    seasons: { duck: "Oct – Nov canvasback specialty Pool 9", goose: "Sept – Nov", turkey: "Spring Eastern turkey", deer: "Oct – Nov" },
    priceStarting: 350,
    priceNotes: "1 of only 8 commercial waterfowlers on Upper Mississippi River; canvasback specialty",
    lodging: "Lodge",
    lodgingIncluded: false,
    mealsIncluded: false,
    tripLength: "1–3 days",
    groupSize: "2–6 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.8,
    description: "One of only 8 licensed commercial waterfowlers on the Upper Mississippi River National Wildlife Refuge. Pool 9 canvasback specialty — 75% of world's canvasback population can concentrate nearby. Also guides Eastern turkey and whitetail deer.",
    highlights: ["1 of only 8 Mississippi River guides", "75% world canvasback population nearby", "Top 10 all-time DU destination", "Eastern turkey and deer also"],
    tags: ["Featured", "Verified"]
  },

  // ── BEAR — IDAHO ────────────────────────────────────────────

  {
    id: "bearpaw-outfitters-id",
    name: "Bearpaw Outfitters",
    verified: true,
    city: "Coeur d'Alene",
    state: "ID",
    stateFull: "Idaho",
    lat: 47.6777,
    lng: -116.7805,
    website: "https://www.bearpawoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Bear", "Elk", "Mule Deer", "Whitetail Deer", "Cougar", "Moose"],
    methods: ["Rifle", "Archery", "Hound Hunting", "Bait"],
    tripTypes: ["Guided", "Unguided", "Drop Camp"],
    seasons: { bear: "Spring and Fall", elk: "Sept – Nov" },
    priceStarting: 2800,
    priceNotes: "Bear hunt starting price; multiple species available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–6 hunters",
    successRate: "100%",
    landType: "Both",
    rating: 4.9,
    description: "Family-run outfitter in business since 1977 — 48 years experience. A+ BBB rating. Idaho rated #1 bear hunting state. Hunts 353 sq mile area with color phase bears. OTC tags — no draw required.",
    highlights: ["48 years in business", "A+ BBB rating", "353 sq mile hunting area", "No draw required", "Color phase bears"],
    tags: ["Featured", "Verified"]
  },

  // ── BEAR — ALASKA ───────────────────────────────────────────

  {
    id: "alaska-brown-bear-adventures-ak",
    name: "Alaska Brown Bear Adventures",
    verified: true,
    city: "Fairbanks",
    state: "AK",
    stateFull: "Alaska",
    lat: 64.8378,
    lng: -147.7164,
    website: "https://alaskabrownbear.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Bear", "Moose", "Caribou"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { bear: "Spring May – June and Fall Oct" },
    priceStarting: 12000,
    priceNotes: "Non-residents must use licensed Alaska guide; harvest ticket required",
    lodging: "Tent Camp",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "10–14 days",
    groupSize: "1–2 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.8,
    description: "Alaska brown and grizzly bear hunting out of Fairbanks. Non-residents legally required to use a licensed Alaska guide. Remote wilderness camp hunts.",
    highlights: ["Required guide for non-residents", "Remote wilderness", "Spring and fall seasons", "Trophy class bears"],
    tags: ["Featured", "Verified"]
  },

  // ── DEER — ILLINOIS / WISCONSIN / IOWA / OHIO / KENTUCKY ────

  {
    id: "boneyard-outfitters-il",
    name: "Boneyard Outfitters",
    verified: true,
    city: "Whittington",
    state: "IL",
    stateFull: "Illinois",
    lat: 37.9500,
    lng: -88.8500,
    website: "https://boneyardoutfitters.com/",
    phone: "(618) 927-3432",
    email: "",
    image: "",
    species: ["Whitetail Deer"],
    methods: ["Firearm", "Archery", "Muzzleloader"],
    tripTypes: ["Guided"],
    seasons: { archery: "Oct", firearm: "Nov – Dec", muzzleloader: "Dec" },
    priceStarting: 2100,
    priceNotes: "Oct archery $2,100; Nov gun $2,700; combo $3,900",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–7 days",
    groupSize: "1–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.7,
    description: "Trophy Southern Illinois whitetail on thousands of acres of private land. High deer density. All food and lodging included. Two-buck combo hunts available.",
    highlights: ["Southern Illinois trophy whitetails", "All inclusive", "Two-buck combo available"],
    tags: ["Verified"]
  },

  {
    id: "wilderness-whitetails-wi",
    name: "Wilderness Whitetails",
    verified: true,
    city: "Central Wisconsin",
    state: "WI",
    stateFull: "Wisconsin",
    lat: 44.5000,
    lng: -89.8000,
    website: "https://www.wildernesswhitetails.com/",
    phone: "(715) 572-3344",
    email: "",
    image: "",
    species: ["Whitetail Deer"],
    methods: ["Archery"],
    tripTypes: ["Guided"],
    seasons: { archery: "Oct – Nov" },
    priceStarting: 5000,
    priceNotes: "All-inclusive 1-on-1 guided; airport transportation from CWA included",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "In operation since 1999 with 90%+ hunter return rate. Specializes in 200+ class typical and non-typical trophy whitetails. All hunts 1-on-1 guided. Transportation from Central Wisconsin Airport included.",
    highlights: ["90%+ return rate", "200+ class deer", "1-on-1 guided", "Airport transportation included"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "iowa-hunting-guides-ia",
    name: "Iowa Hunting Guides",
    verified: true,
    city: "Des Moines",
    state: "IA",
    stateFull: "Iowa",
    lat: 41.5868,
    lng: -93.6250,
    website: "https://iowahuntingguides.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Whitetail Deer", "Turkey"],
    methods: ["Archery", "Firearm"],
    tripTypes: ["Guided"],
    seasons: { archery: "Oct – Nov", firearm: "Dec", turkey: "April – May" },
    priceStarting: 2500,
    priceNotes: "Non-resident firearm deer is draw-only; archery better availability",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "3–5 days",
    groupSize: "1–6 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.5,
    description: "Iowa consistently produces Boone and Crockett record book entries. Non-resident firearm tags are draw-only; archery tags have better availability. Tag application guidance provided.",
    highlights: ["Trophy Iowa whitetails", "B&C quality deer", "Tag application guidance"],
    tags: ["Verified"]
  },

  // ── KENTUCKY ────────────────────────────────────────────────

  {
    id: "lost-mountain-outfitters-ky",
    name: "Lost Mountain Outfitters",
    verified: true,
    city: "Eastern Kentucky",
    state: "KY",
    stateFull: "Kentucky",
    lat: 37.3000,
    lng: -82.9000,
    website: "http://www.lostmountainoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Whitetail Deer", "Turkey"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { elk: "Draw required Jan–Apr; rut season hunts", deer: "Sept – Jan", turkey: "Spring April – May" },
    priceStarting: 4500,
    priceNotes: "Elk guided hunts $4,500+; deer and turkey also available",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Kentucky's premiere elk, deer, and turkey outfitter in the 16-county elk restoration zone in Eastern Kentucky. Kentucky holds the highest elk population of any state east of the Mississippi at approximately 10,000 animals. Full field-to-freezer service.",
    highlights: ["Eastern KY elk restoration zone — 16 counties", "Largest elk herd east of the Mississippi", "Field to freezer full service", "Elk deer and turkey all available"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "kentucky-bulls-and-beards-ky",
    name: "Kentucky Bulls and Beards Guide Service",
    verified: true,
    city: "Lily",
    state: "KY",
    stateFull: "Kentucky",
    lat: 37.0700,
    lng: -84.1100,
    website: "https://www.kentuckybullsandbeardsguideservice.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk", "Turkey"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { elk: "Draw required Jan–Apr application", turkey: "Spring Eastern turkey" },
    priceStarting: 4500,
    priceNotes: "Kentucky Licensed Commercial Hunting Guide; President of Kentucky Elk Guide Association",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–4 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Kentucky Licensed Commercial Hunting Guide and licensed taxidermist. President of the Kentucky Elk Guide Association — the highest level of elk guide credentialing in the state.",
    highlights: ["President of Kentucky Elk Guide Association", "Kentucky Licensed Commercial Guide", "State and federal licensed taxidermist"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "kentucky-wild-outdoors-ky",
    name: "Kentucky Wild Outdoors",
    verified: true,
    city: "Lexington",
    state: "KY",
    stateFull: "Kentucky",
    lat: 38.0406,
    lng: -84.5037,
    website: "https://www.kentuckywildoutdoors.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Elk"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { elk: "Draw required; guided hunts for permit holders" },
    priceStarting: 4500,
    priceNotes: "50+ years experience; charter member Kentucky Elk Guide Association",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "5–7 days",
    groupSize: "1–2 hunters",
    successRate: "",
    landType: "Both",
    rating: 4.9,
    description: "Owner-guide Bill Carman has 50+ years hunting and fishing experience in the Kentucky wilds. Charter member of the Kentucky Elk Guide Association. Former Regional Director for the Rocky Mountain Elk Foundation for 10 years.",
    highlights: ["50+ years KY hunting experience", "Former RMEF Regional Director", "Charter member Kentucky Elk Guide Association"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "premier-outfitters-ky",
    name: "Premier Outfitters",
    verified: true,
    city: "Western Kentucky",
    state: "KY",
    stateFull: "Kentucky",
    lat: 37.0000,
    lng: -87.5000,
    website: "https://premieroutfitters.com/",
    phone: "(864) 938-8699",
    email: "",
    image: "",
    species: ["Whitetail Deer", "Turkey"],
    methods: ["Rifle", "Archery", "Muzzleloader"],
    tripTypes: ["Guided"],
    seasons: { deer: "Sept – Jan", turkey: "Spring Eastern turkey April – May" },
    priceStarting: 2500,
    priceNotes: "17+ years; named Dream Camp by Deer and Deer Hunting magazine",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "4–6 days",
    groupSize: "2–12 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "In operation since 2008. Named Dream Camp by Deer and Deer Hunting magazine. One of the top bow-hunting destinations for whitetail in the country. Thousands of privately managed acres in Western Kentucky. 100% fair chase.",
    highlights: ["Named Dream Camp by Deer and Deer Hunting magazine", "17+ years in operation", "Top bow-hunting destination nationally", "100% fair chase"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "whitetail-heaven-outfitters-ky",
    name: "Whitetail Heaven Outfitters",
    verified: true,
    city: "Central Kentucky",
    state: "KY",
    stateFull: "Kentucky",
    lat: 37.8393,
    lng: -84.2700,
    website: "https://whitetailheavenoutfitters.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Whitetail Deer", "Turkey"],
    methods: ["Rifle", "Archery", "Muzzleloader", "Crossbow"],
    tripTypes: ["Guided"],
    seasons: { deer: "Sept – Jan", turkey: "Spring" },
    priceStarting: 2500,
    priceNotes: "25,000+ acres; 21+ years; handicap accessible; also hunts Ohio Indiana Kansas and Florida",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "4–6 days",
    groupSize: "2–16 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.9,
    description: "21+ years and 25,000+ acres across Central Kentucky, Southern Ohio, and Southern Indiana. Kentucky holds the 6th biggest typical buck ever harvested in the world. Handicap accessible. Also offers hunts in Kansas and Florida.",
    highlights: ["21+ years operation", "25,000+ acres KY OH and IN", "6th biggest typical buck world record nearby", "Handicap accessible"],
    tags: ["Featured", "Verified"]
  },

  {
    id: "salt-river-outfitters-ky",
    name: "Salt River Outfitters",
    verified: true,
    city: "Bourbon Trail area",
    state: "KY",
    stateFull: "Kentucky",
    lat: 37.9000,
    lng: -85.1000,
    website: "https://saltriverhunts.com/",
    phone: "",
    email: "",
    image: "",
    species: ["Whitetail Deer"],
    methods: ["Rifle", "Archery"],
    tripTypes: ["Guided"],
    seasons: { deer: "Archery and rifle seasons" },
    priceStarting: 2000,
    priceNotes: "Located on the Kentucky Bourbon Trail; distillery tours available during stay",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: true,
    tripLength: "4–6 days",
    groupSize: "2–10 hunters",
    successRate: "",
    landType: "Private",
    rating: 4.8,
    description: "Kentucky whitetail outfitter on the famous Bourbon Trail with multiple distilleries within 30 minutes. Consistent 5-star reviews. A unique combination of world-class whitetail hunting and Kentucky bourbon culture.",
    highlights: ["On the Kentucky Bourbon Trail", "Distillery tours can be arranged", "Consistent 5-star reviews"],
    tags: ["Verified"]
  },

  {
    id: "fins-to-feathers-ky",
    name: "Fins to Feathers Outfitters",
    verified: true,
    city: "Grand Rivers",
    state: "KY",
    stateFull: "Kentucky",
    lat: 37.0000,
    lng: -88.2300,
    website: "https://finstofeathers.net/",
    phone: "",
    email: "",
    image: "",
    species: ["Waterfowl"],
    methods: ["Shotgun"],
    tripTypes: ["Guided"],
    seasons: { duck: "Late Nov – Jan Kentucky Lake and Lake Barkley diver ducks" },
    priceStarting: 300,
    priceNotes: "Pontoon blinds and layout boats; canvasback and redhead specialty",
    lodging: "Lodge",
    lodgingIncluded: true,
    mealsIncluded: false,
    tripLength: "1–3 days",
    groupSize: "2–8 hunters",
    successRate: "",
    landType: "Public",
    rating: 4.7,
    description: "Guided diver duck hunts on Kentucky Lake and Lake Barkley in the Land Between the Lakes region. Specialty in canvasback and redhead. Pontoon blinds and layout boats.",
    highlights: ["Kentucky Lake and Lake Barkley", "Canvasback and redhead specialty", "Land Between the Lakes region"],
    tags: ["Verified"]
  }

];

// ── Helper functions ────────────────────────────────────────

function getOutfitterById(id) {
  return OUTFITTERS.find(o => o.id === id);
}

function getOutfittersBySpecies(species) {
  return OUTFITTERS.filter(o =>
    o.species.some(s => s.toLowerCase() === species.toLowerCase())
  );
}

function getOutfittersByState(state) {
  return OUTFITTERS.filter(o =>
    o.state.toUpperCase() === state.toUpperCase() ||
    o.stateFull.toLowerCase() === state.toLowerCase()
  );
}

function getFeaturedOutfitters() {
  return OUTFITTERS.filter(o => o.tags && o.tags.includes("Featured"));
}

function toSlug(name) {
  return name.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
