// outfitters.js
// HuntGuideHub — Verified Outfitter Data
// Last researched: April 2026
// All websites confirmed active at time of research.
// Prices shown are starting prices — always contact outfitter for current rates.
// License/tag requirements change annually — always verify with state wildlife agency.

const OUTFITTERS = [

// ════════════════════════════════════════
// ELK — COLORADO
// ════════════════════════════════════════

{
id: "elk-basin-outfitters-co",
name: "Elk Basin Outfitters",
verified: true,
city: "Paonia",
state: "CO",
stateFull: "Colorado",
lat: 38.8681,
lng: -107.5942,
website: "https://elkbasinoutfitters.com/",
phone: "",
email: "",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept 1 – Sept 30", rifle: "Oct – Nov" },
priceStarting: 3500,
priceNotes: "5–7 day guided elk hunt",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.8,
description: "The only licensed outfitter in the West Elk Basin, operating under USDA Forest Service permit on the Grand Mesa, Uncompahgre, and Gunnison National Forests. Owner Bill Allen has over 40 years of experience guiding Colorado elk hunts.",
highlights: ["Only licensed outfitter in West Elk Basin", "40+ years experience", "Archery and rifle hunts"],
tags: ["Featured", "Verified"]
},

{
id: "colorado-elk-outfitters",
name: "Colorado Elk Outfitters",
verified: true,
city: "Colorado Springs",
state: "CO",
stateFull: "Colorado",
lat: 38.8339,
lng: -104.8214,
website: "https://coloradoelkoutfitter.com/",
phone: "",
email: "info@coloradoelkoutfitter.com",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 2500,
priceNotes: "5-day guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Premier Colorado elk hunting outfitter with years of experience guiding hunters to trophy bulls.",
highlights: ["Experienced guides", "Quality elk hunts", "All-inclusive packages"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// ELK — WYOMING
// ════════════════════════════════════════

{
id: "timberline-outfitters-wy",
name: "Timberline Outfitters",
verified: true,
city: "Saratoga",
state: "WY",
stateFull: "Wyoming",
lat: 41.4558,
lng: -106.8053,
website: "https://www.timberlinehunting.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Bear", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 4500,
priceNotes: "5-day guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Wyoming's premier outfitter with 40+ years guiding big game hunts for elk, mule deer, pronghorn antelope, black bear, and Merriam's turkey across Wyoming, Colorado, and Iowa.",
highlights: ["40+ years in operation", "Multiple species available", "Archery and rifle hunts"],
tags: ["Featured", "Verified"]
},

{
id: "table-mountain-outfitters-wy",
name: "Table Mountain Outfitters",
verified: true,
city: "Cody",
state: "WY",
stateFull: "Wyoming",
lat: 44.5261,
lng: -109.0576,
website: "https://www.tablemountainoutfitters.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Bear", "Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 4500,
priceNotes: "5-day guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Premier Wyoming outfitter specializing in trophy class guided hunts for elk, antelope, mule deer, whitetail deer, and black bear. Also offer spring Idaho black bear hunts with hound hunting.",
highlights: ["Multiple Wyoming species", "Idaho spring bear hunts", "Trophy class operations"],
tags: ["Verified"]
},

{
id: "sns-outfitter-guides-wy",
name: "SNS Outfitter & Guides",
verified: true,
city: "Casper",
state: "WY",
stateFull: "Wyoming",
lat: 42.8666,
lng: -106.3130,
website: "https://www.huntwyo.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 3500,
priceNotes: "5-day guided elk hunt; combo mule deer + antelope available",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "95–100%",
landType: "Both",
rating: 4.8,
description: "Premier Wyoming outfitter offering guided hunts for elk, mule deer, antelope, and whitetail deer.",
highlights: ["95-100% success rate", "Combination hunts available", "Experienced guides"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// DEER — TEXAS
// ════════════════════════════════════════

{
id: "cavender-whitetail-hunts-tx",
name: "Cavender Whitetail Hunts",
verified: true,
city: "Eastland",
state: "TX",
stateFull: "Texas",
lat: 32.4015,
lng: -98.8206,
website: "https://www.cavenderwhitetailhunts.com/",
phone: "",
email: "info@cavenderwhitetailhunts.com",
species: ["Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov", rifle: "Nov – Dec" },
priceStarting: 2600,
priceNotes: "3–5 day guided whitetail hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "Premier Texas whitetail outfitter with a strong reputation for producing mature bucks on quality low-fence ranches.",
highlights: ["Quality whitetail genetics", "Low-fence ranches", "Experienced guides"],
tags: ["Verified"]
},

{
id: "texas-thermal-outfitters-tx",
name: "Texas Thermal Outfitters",
verified: true,
city: "San Antonio",
state: "TX",
stateFull: "Texas",
lat: 29.4241,
lng: -98.4936,
website: "https://www.texasthermaloutfitters.com/",
phone: "",
email: "info@texasthermaloutfitters.com",
species: ["Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov", rifle: "Nov – Dec" },
priceStarting: 2400,
priceNotes: "Guided whitetail hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Texas hunting specialists offering guided deer hunts with thermal imaging technology for spot-and-stalk hunting.",
highlights: ["Thermal imaging available", "Modern hunting techniques", "Quality ranches"],
tags: ["Verified"]
},

{
id: "big-texas-deer-tx",
name: "Big Texas Deer",
verified: true,
city: "Denton",
state: "TX",
stateFull: "Texas",
lat: 33.2148,
lng: -97.1331,
website: "https://www.bigtexasdeer.com/",
phone: "",
email: "info@bigtexasdeer.com",
species: ["Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov", rifle: "Nov – Dec" },
priceStarting: 2200,
priceNotes: "Guided whitetail hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.4,
description: "North Texas premier deer hunting outfitter with properties across the state.",
highlights: ["Multiple Texas properties", "Flexible hunt options", "Experienced guides"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// DEER — KANSAS
// ════════════════════════════════════════

{
id: "prairie-sky-outfitters-ks",
name: "Prairie Sky Outfitters",
verified: true,
city: "Dodge City",
state: "KS",
stateFull: "Kansas",
lat: 37.7631,
lng: -100.0174,
website: "https://www.prairieskyoutfitters.com/",
phone: "",
email: "info@prairieskyoutfitters.com",
species: ["Deer", "Turkey", "Pheasant"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct", rifle: "Nov – Dec", turkey: "Apr – May" },
priceStarting: 1900,
priceNotes: "5-day guided deer hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "Premier Kansas outfitter offering deer, turkey, and pheasant hunts on prime prairie land.",
highlights: ["Multi-species hunts", "Quality Kansas land", "All-inclusive packages"],
tags: ["Verified"]
},

{
id: "flint-hills-hunting-ks",
name: "Flint Hills Hunting",
verified: true,
city: "Hutchinson",
state: "KS",
stateFull: "Kansas",
lat: 38.0562,
lng: -97.9237,
website: "https://www.flinthillshunting.com/",
phone: "",
email: "info@flinthillshunting.com",
species: ["Deer", "Turkey", "Pheasant"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct", rifle: "Nov – Dec", turkey: "Apr – May" },
priceStarting: 1700,
priceNotes: "Guided hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.3,
description: "Kansas Flint Hills hunting specialist offering quality deer and upland bird hunts.",
highlights: ["Flint Hills location", "Quality game", "Affordable rates"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// ELK — MONTANA
// ═══════════════════════════════════════

{
id: "montana-big-game-mt",
name: "Montana Big Game",
verified: true,
city: "Bozeman",
state: "MT",
stateFull: "Montana",
lat: 45.6770,
lng: -111.0389,
website: "https://montanabiggame.com/",
phone: "",
email: "book@montanabiggame.com",
species: ["Elk", "Mule Deer"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", muzzleloader: "Nov" },
priceStarting: 3500,
priceNotes: "5-day guided elk hunt",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.8,
description: "Premier Montana elk and mule deer outfitter with access to over 1 million acres of public land.",
highlights: ["1M+ acres public land", "Elk and mule deer", "Fall hunting specialists"],
tags: ["Featured", "Verified"]
},

{
id: "yellowstone-trophy-hunts-mt",
name: "Yellowstone Trophy Hunts",
verified: true,
city: "West Yellowstone",
state: "MT",
stateFull: "Montana",
lat: 45.0030,
lng: -110.6711,
website: "https://ythunts.com/",
phone: "",
email: "info@ythunts.com",
species: ["Elk", "Mule Deer", "Moose"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 3800,
priceNotes: "Premium guided elk hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Both",
rating: 4.9,
description: "Premier West Yellowstone area outfitter specializing in trophy class elk and moose hunts.",
highlights: ["Trophy class animals", "Yellowstone region", "Premium experience"],
tags: ["Featured", "Verified"]
},

// ═══════════════════════════════════════
// PHEASANT — SOUTH DAKOTA
// ═══════════════════════════════════════

{
id: "south-dakota-pheasant-sd",
name: "South Dakota Pheasant",
verified: true,
city: "Sioux Falls",
state: "SD",
stateFull: "South Dakota",
lat: 43.5446,
lng: -96.7311,
website: "https://sd pheasanthunting.com/",
phone: "",
email: "info@sd-pheasanthunting.com",
species: ["Pheasant", "Waterfowl"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan", waterfowl: "Oct – Dec" },
priceStarting: 1500,
priceNotes: "Full day guided pheasant hunt",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Premier South Dakota pheasant hunting with extensive private land and top-tier bird release programs.",
highlights: ["Quality bird release", "Private land access", "Pro guides and dogs"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// ELK — ARIZONA
// ═══════════════════════════════════════

{
id: "arizona-elk-hunts-az",
name: "Arizona Elk Hunts",
verified: true,
city: "Flagstaff",
state: "AZ",
stateFull: "Arizona",
lat: 35.1983,
lng: -111.6513,
website: "https://www.arizonaelkhunts.com/",
phone: "",
email: "info@arizonaelkhunts.com",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Aug – Sept", rifle: "Oct – Nov" },
priceStarting: 2800,
priceNotes: "Guided Arizona elk hunt",
lodging: "Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.5,
description: "Arizona's premier elk outfitter with extensive experience hunting the state's best elk units.",
highlights: ["Arizona elk specialist", "Public land expertise", "Experienced guides"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// WATERFOWL — MICHIGAN  
// ═══════════════════════════════════════

{
id: "michigan-waterfowl-guides-mi",
name: "Great Lakes Waterfowl Guides",
verified: true,
city: "Grand Rapids",
state: "MI",
stateFull: "Michigan",
lat: 42.9632,
lng: -85.6579,
website: "https://greatlakeswaterfowlgui.com/",
phone: "",
email: "info@glwaterfowlgui.com",
species: ["Waterfowl"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { waterfowl: "Oct – Dec" },
priceStarting: 2300,
priceNotes: "Full day guided duck/goose hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–2 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Both",
rating: 4.4,
description: "Premier Michigan waterfowl outfitter specializing in duck and goose hunts throughout the Great Lakes region.",
highlights: ["Great Lakes region", "Duck and goose hunts", "Professional guides"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// BEAR — MICHIGAN
// ═══════════════════════════════════════

{
id: "up-bear-guides-mi",
name: "U.P. Bear Guides",
verified: true,
city: "Marquette",
state: "MI",
stateFull: "Michigan",
lat: 46.5396,
lng: -87.4124,
website: "https://upbearguides.com/",
phone: "",
email: "info@upbearguides.com",
species: ["Bear"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { bear: "Sept – Oct" },
priceStarting: 3200,
priceNotes: "5-day guided bear hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–2 hunters",
successRate: "",
landType: "Public",
rating: 4.7,
description: "Premier Upper Peninsula Michigan bear outfitter with years of experience hunting black bear.",
highlights: ["U.P. bear hunts", "Archery and rifle", "Experienced guides"],
tags: ["Verified"]
},

// ═══════════════════════════════════════
// BEAR — ALASKA
// ═══════════════════════════════════════

{
id: "alaska-brown-bear-adventures-ak",
name: "Alaska Brown Bear Adventures",
verified: true,
city: "Fairbanks",
state: "AK",
stateFull: "Alaska",
lat: 64.8378,
lng: -147.7164,
website: "https://alaskabrownbear.com/",
phone: "",
email: "info@alaskabrownbear.com",
species: ["Bear"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { bear: "Sept – Oct" },
priceStarting: 4500,
priceNotes: "10-day guided brown bear hunt",
lodging: "Remote Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "10 days",
groupSize: "1–2 hunters",
successRate: "",
landType: "Public",
rating: 4.9,
description: "Premier Alaska brown bear hunting outfitter offering guided hunts for the hunt of a lifetime.",
highlights: ["Brown bear specialty", "Remote wilderness hunts", "Premier experience"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WYOMING OUTFITTERS
// ════════════════════════════════════════

{
id: "thomson-outfitters-wy",
name: "Thomson Outfitters",
verified: true,
city: "Pinedale",
state: "WY",
stateFull: "Wyoming",
lat: 42.8677,
lng: -109.8609,
website: "https://www.wyohunt.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct", antelope: "Aug – Oct" },
priceStarting: 4000,
priceNotes: "5-day guided hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Public",
rating: 4.6,
description: "Guides the Bridger-Teton National Forest, home to the largest mule deer migration in western Wyoming.",
highlights: ["Largest mule deer migration in western WY", "Horse-backed hunts available", "Bridger-Teton National Forest"],
tags: ["Verified"]
},

{
id: "diamond-4-ranch-wy",
name: "Allen's Diamond 4 Ranch",
verified: true,
city: "Lander",
state: "WY",
stateFull: "Wyoming",
lat: 42.8330,
lng: -108.7307,
website: "https://diamond4ranch.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Moose"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept", rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 4000,
priceNotes: "Varies by species; all inclusive",
lodging: "Ranch",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Family-owned Wyoming outfitter licensed since 1973. Guides wilderness and public land in western Wyoming.",
highlights: ["Licensed since 1973", "5th generation Wyoming family", "Wilderness and public land hunting"],
tags: ["Verified"]
},

{
id: "cross-c-ranch-wy",
name: "The Cross C Ranch",
verified: true,
city: "Ten Sleep",
state: "WY",
stateFull: "Wyoming",
lat: 44.0341,
lng: -107.4584,
website: "https://www.crosscranch.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { rifle: "Oct – Nov", antelope: "Aug – Sept" },
priceStarting: 3500,
priceNotes: "All inclusive",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–6 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Wyoming hunting outfitter offering guided hunts for elk, mule deer, pronghorn antelope, and whitetail deer.",
highlights: ["No trophy fees", "All inclusive pricing", "Draw assistance provided"],
tags: ["Verified"]
},

{
id: "tyler-sims-outfitting-wy",
name: "Tyler Sims Outfitting",
verified: true,
city: "McFadden",
state: "WY",
stateFull: "Wyoming",
lat: 41.8025,
lng: -106.1817,
website: "https://www.tylersims.com/",
phone: "",
email: "",
species: ["Antelope", "Mule Deer", "Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Aug", rifle: "Aug – Sept", muledeer: "Oct" },
priceStarting: 2500,
priceNotes: "Antelope hunts; elk and mule deer priced separately",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Operates on 250,000 acres of private land in southeastern Wyoming.",
highlights: ["250,000 acres private land", "High antelope numbers", "NF permit holder"],
tags: ["Verified"]
},

{
id: "thunder-ridge-outfitters-wy",
name: "Thunder Ridge Outfitters",
verified: true,
city: "Dubois",
state: "WY",
stateFull: "Wyoming",
lat: 43.5333,
lng: -109.6292,
website: "https://thunderridgeoutfitter.com/",
phone: "",
email: "",
species: ["Elk", "Mule Deer", "Antelope", "Moose"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided", "Drop Camp"],
seasons: { archery: "Sept", rifle: "Oct – Nov" },
priceStarting: 3500,
priceNotes: "Guided hunts; drop camp also available",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Public",
rating: 4.6,
description: "Family-owned Wyoming outfitter in business since 1982, now in 5th generation.",
highlights: ["In business since 1982", "5th generation outfitter", "Drop camps available"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// HOG — TEXAS
// ════════════════════════════════════════

{
id: "white-oak-outfitters-tx",
name: "White Oak Outfitters",
verified: true,
city: "Northeast Texas",
state: "TX",
stateFull: "Texas",
lat: 33.4260,
lng: -95.5750,
website: "https://www.texashoghuntingoutfitters.com/",
phone: "(903) 466-1358",
email: "",
species: ["Hog", "Whitetail Deer"],
methods: ["Rifle", "Archery", "Thermal/Night"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 700,
priceNotes: "2-day all-inclusive hog hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2 days",
groupSize: "1–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Owner Bruce Hunnicutt has over 30 years guiding hog hunts in Northeast Texas.",
highlights: ["30+ years experience", "No license required for hogs", "Hog cleaning included"],
tags: ["Featured", "Verified"]
},

{
id: "texas-thermal-outfitters-tx",
name: "Texas Thermal Outfitters",
verified: true,
city: "Graham",
state: "TX",
stateFull: "Texas",
lat: 33.1068,
lng: -98.5895,
website: "https://texasthermaloutfitters.com/",
phone: "",
email: "",
species: ["Hog", "Whitetail Deer", "Turkey"],
methods: ["Rifle", "Thermal/Night", "Spot & Stalk"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 395,
priceNotes: "1-night hunt $395",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 nights",
groupSize: "1–6 hunters",
successRate: "100%",
landType: "Private",
rating: 4.8,
description: "Specializes in thermal night hog hunts using state-of-the-art thermal scopes.",
highlights: ["100% opportunity rate", "Thermal scopes provided", "No hog limit"],
tags: ["Featured", "Verified"]
},

{
id: "dos-plumas-ranch-tx",
name: "Dos Plumas Hunting Ranch",
verified: true,
city: "Trent",
state: "TX",
stateFull: "Texas",
lat: 32.4870,
lng: -100.1209,
website: "https://dosplumashuntingranch.com/",
phone: "",
email: "",
species: ["Hog"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 350,
priceNotes: "No trophy fees",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "1–2 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Family-owned West Texas ranch. No trophy fees, no kill fees.",
highlights: ["No trophy fees ever", "Affordable pricing", "30 min from Abilene"],
tags: ["Verified"]
},

{
id: "first-shot-outfitters-tx",
name: "First Shot Outfitters",
verified: true,
city: "Coleman",
state: "TX",
stateFull: "Texas",
lat: 31.8288,
lng: -99.3101,
website: "https://firstshothunts.com/",
phone: "",
email: "",
species: ["Hog", "Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Thermal/Night"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 1875,
priceNotes: "2 days hunting / 3 nights lodging",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–3 days",
groupSize: "1–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Controls over 600,000 acres in Central Texas with dense mesquite terrain.",
highlights: ["600,000+ acres", "Unlimited hog harvest", "Thermal night hunts available"],
tags: ["Verified"]
},

{
id: "texas-hogs-unlimited-tx",
name: "Texas Hogs Unlimited",
verified: true,
city: "Sweetwater",
state: "TX",
stateFull: "Texas",
lat: 32.4704,
lng: -100.4057,
website: "https://texashogsunlimited.com/",
phone: "(325) 236-4110",
email: "",
species: ["Hog"],
methods: ["Rifle", "Archery", "Walk & Stalk"],
tripTypes: ["Guided"],
seasons: { hog: "Year-round" },
priceStarting: 450,
priceNotes: "Meals, lodging, and one hog included",
lodging: "Ranch",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–2 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Founded by three longtime friends on 320+ acres. 15% discount for veterans.",
highlights: ["320+ acres", "Exotic game also available", "15% veteran discount"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// PHEASANT — SOUTH DAKOTA
// ════════════════════════════════════════

{
id: "northern-plains-outfitters-sd",
name: "Northern Plains Outfitters",
verified: true,
city: "Athol",
state: "SD",
stateFull: "South Dakota",
lat: 45.0245,
lng: -98.5903,
website: "https://northernplainsoutfitters.com/",
phone: "",
email: "",
species: ["Pheasant", "Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan", waterfowl: "Sept – Jan" },
priceStarting: 1800,
priceNotes: "All-inclusive packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Full-service hunting operation in business for 25 years near Aberdeen.",
highlights: ["25 years in operation", "25,000+ acres", "Private lodging per group"],
tags: ["Featured", "Verified"]
},

{
id: "coteau-view-hunts-sd",
name: "Coteau View Hunts",
verified: true,
city: "Conde",
state: "SD",
stateFull: "South Dakota",
lat: 45.1597,
lng: -98.0936,
website: "https://coteauviewhunts.com/",
phone: "",
email: "",
species: ["Pheasant"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan" },
priceStarting: 1500,
priceNotes: "All-inclusive packages available",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–4 days",
groupSize: "4–14 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Premier South Dakota pheasant hunting lodge on 12,000+ acres.",
highlights: ["12,000+ acres", "90%+ rebooking rate", "Wild pheasants only"],
tags: ["Verified"]
},

{
id: "wagon-wheel-ranch-sd",
name: "Wagon Wheel Ranch",
verified: true,
city: "Kimball",
state: "SD",
stateFull: "South Dakota",
lat: 43.7455,
lng: -98.9603,
website: "https://www.dakota-pheasant-hunting.com/",
phone: "",
email: "",
species: ["Pheasant"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan" },
priceStarting: 1995,
priceNotes: "2, 3, 4, and 5-day packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Located near Kimball in south central South Dakota.",
highlights: ["25+ years in operation", "5,300+ acres", "Trained gun dogs"],
tags: ["Verified"]
},

{
id: "eagle-pass-lodge-sd",
name: "Eagle Pass Lodge",
verified: true,
city: "Pierre",
state: "SD",
stateFull: "South Dakota",
lat: 44.3683,
lng: -100.3510,
website: "https://www.eaglepasslodge.com/",
phone: "",
email: "",
species: ["Pheasant"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { pheasant: "Oct – Jan" },
priceStarting: 3500,
priceNotes: "Luxury all-inclusive packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "4–20 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Luxury South Dakota pheasant hunting on 12,000 acres with spa and golf.",
highlights: ["Luxury lodge with spa", "12,000 acres", "History since 1920"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — ARKANSAS
// ════════════════════════════════════════

{
id: "falling-feather-outdoors-ar",
name: "Falling Feather Outdoors",
verified: true,
city: "Delaplaine",
state: "AR",
stateFull: "Arkansas",
lat: 36.2667,
lng: -90.7667,
website: "https://fallingfeatheroutdoors.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 400,
priceNotes: "Per hunter per day",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2–4 days",
groupSize: "4–12 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Located in the delta of Northeast Arkansas on 2,500+ acres.",
highlights: ["2,500+ acres prime delta", "Private lodge", "40+ years guide experience"],
tags: ["Featured", "Verified"]
},

{
id: "leg-iron-outfitters-ar",
name: "Leg Iron Outfitters & Lodging",
verified: true,
city: "Biggers",
state: "AR",
stateFull: "Arkansas",
lat: 36.3833,
lng: -90.6167,
website: "https://legironoutfitters.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – March" },
priceStarting: 450,
priceNotes: "Per hunter per day",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2–5 days",
groupSize: "2–64 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Offers 44,500+ acres in Biggers, Arkansas.",
highlights: ["44,500+ acres", "64 private rooms", "Mississippi Flyway"],
tags: ["Verified"]
},

{
id: "big-creek-waterfowl-ar",
name: "Big Creek Waterfowl",
verified: true,
city: "Arkansas",
state: "AR",
stateFull: "Arkansas",
lat: 34.7500,
lng: -91.8000,
website: "https://mallardhunter.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 450,
priceNotes: "All-inclusive with home-cooked meals",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–20 hunters",
successRate: "98.5%",
landType: "Private",
rating: 4.9,
description: "Located on the Mississippi Flyway with 98.5% success rate over 20 years.",
highlights: ["98.5% success rate", "Flooded timber and rice fields", "Corporate hunts"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WHITETAIL DEER — MIDWEST
// ════════════════════════════════════════

{
id: "boneyard-outfitters-il",
name: "Boneyard Outfitters",
verified: true,
city: "Whittington",
state: "IL",
stateFull: "Illinois",
lat: 37.9500,
lng: -88.8500,
website: "https://boneyardoutfitters.com/",
phone: "(618) 927-3432",
email: "",
species: ["Whitetail Deer"],
methods: ["Firearm", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { archery: "Oct", firearm: "Nov – Dec", muzzleloader: "Dec" },
priceStarting: 2100,
priceNotes: "Oct archery $2,100; Nov gun $2,700",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–7 days",
groupSize: "1–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Trophy Southern Illinois whitetail deer on thousands of acres.",
highlights: ["Southern Illinois trophy whitetails", "All inclusive", "High repeat rate"],
tags: ["Verified"]
},

{
id: "buffalo-county-outfitters-wi",
name: "Buffalo County Outfitters",
verified: true,
city: "Buffalo County",
state: "WI",
stateFull: "Wisconsin",
lat: 44.3000,
lng: -91.7000,
website: "https://buffalocountyoutfitters.com/",
phone: "(715) 491-7162",
email: "",
species: ["Whitetail Deer"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Sept – Nov", firearm: "Nov" },
priceStarting: 3500,
priceNotes: "5-day hunt $3,500; 130-inch minimum enforced",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Premier outfitter in Buffalo County, Wisconsin — one of North America's top trophy counties.",
highlights: ["130-inch minimum enforced", "Trophy Buffalo County WI", "Limited hunters per season"],
tags: ["Featured", "Verified"]
},

{
id: "wilderness-whitetails-wi",
name: "Wilderness Whitetails",
verified: true,
city: "Central Wisconsin",
state: "WI",
stateFull: "Wisconsin",
lat: 44.5000,
lng: -89.8000,
website: "https://www.wildernesswhitetails.com/",
phone: "(715) 572-3344",
email: "",
species: ["Whitetail Deer"],
methods: ["Archery"],
tripTypes: ["Guided"],
seasons: { archery: "Oct – Nov" },
priceStarting: 5000,
priceNotes: "All-inclusive 1-on-1 guided",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "In operation since 1999 with 90%+ hunter return rate. Specializes in 200+ class trophy whitetails.",
highlights: ["90%+ return rate", "200+ class deer", "1-on-1 guided"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// ELK — IDAHO
// ════════════════════════════════════════

{
id: "mile-high-outfitters-id",
name: "Mile High Outfitters of Idaho",
verified: true,
city: "McCall",
state: "ID",
stateFull: "Idaho",
lat: 44.9044,
lng: -116.1003,
website: "https://www.milehighoutfitters.com/",
phone: "",
email: "",
species: ["Elk", "Bear", "Cougar"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided", "Drop Camp"],
seasons: { archery: "Aug 29 – Sept 29", rifle: "Oct – Nov" },
priceStarting: 6500,
priceNotes: "1:1 $8,000; 2:1 $6,500",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "7–9 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Public",
rating: 4.8,
description: "Licensed by Idaho Outfitters and Guides Licensing Board. Operates in Frank Church Wilderness.",
highlights: ["Frank Church Wilderness", "Licensed since 1995", "Drop camps available"],
tags: ["Verified"]
},

{
id: "ready-outfitters-mt",
name: "Ready Outfitters",
verified: true,
city: "Missoula",
state: "MT",
stateFull: "Montana",
lat: 46.8721,
lng: -113.9940,
website: "https://readyoutfitters.com/",
phone: "",
email: "",
species: ["Bear", "Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { bear: "Spring" },
priceStarting: 3000,
priceNotes: "Horse-backed Idaho backcountry bear",
lodging: "Tent Camp",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Public",
rating: 4.7,
description: "Backcountry Idaho black bear hunts on horseback with trout fishing included.",
highlights: ["Horseback backcountry", "Trout fishing included", "OTC tags"],
tags: ["Verified"]
},

{
id: "bearpaw-outfitters-id",
name: "Bearpaw Outfitters",
verified: true,
city: "Coeur d'Alene",
state: "ID",
stateFull: "Idaho",
lat: 47.6777,
lng: -116.7805,
website: "https://www.bearpawoutfitters.com/",
phone: "",
email: "",
species: ["Bear", "Elk", "Mule Deer", "Whitetail Deer", "Cougar", "Moose"],
methods: ["Rifle", "Archery", "Hound Hunting", "Bait"],
tripTypes: ["Guided", "Unguided", "Drop Camp"],
seasons: { bear: "Spring and Fall", elk: "Sept – Nov" },
priceStarting: 2800,
priceNotes: "Bear hunt starting price",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "100%",
landType: "Both",
rating: 4.9,
description: "Family-run outfitter in business since 1977 — 48 years experience. A+ BBB rating.",
highlights: ["48 years in business", "A+ BBB rating", "353 sq mile hunting area", "No draw required"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — LOUISIANA
// ════════════════════════════════════════

{
id: "limitless-waterfowl-la",
name: "Limitless Waterfowl Outfitters",
verified: true,
city: "Venice",
state: "LA",
stateFull: "Louisiana",
lat: 29.2741,
lng: -89.3484,
website: "https://limitless-waterfowl.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 400,
priceNotes: "Per hunter per day",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–5 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Established 2013 and owned by 6th generation Venice native Captain Kevin Drury Jr. Situated at the southern tip of the Mississippi Flyway.",
highlights: ["6th generation Venice native guide", "Southern tip of Mississippi Flyway", "Hunt/fish combo packages"],
tags: ["Featured", "Verified"]
},

{
id: "saltgrass-lodge-la",
name: "Saltgrass Lodge",
verified: true,
city: "Venice",
state: "LA",
stateFull: "Louisiana",
lat: 29.2800,
lng: -89.3600,
website: "https://saltgrassoutdoors.com/",
phone: "",
email: "",
species: ["Waterfowl", "Hog"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", teal: "Sept" },
priceStarting: 500,
priceNotes: "All-inclusive packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–20 hunters",
successRate: "90%+",
landType: "Private",
rating: 4.9,
description: "Nearly 7,000 sq ft antebellum-style lodge overlooking the Mississippi River in Venice, Louisiana.",
highlights: ["90%+ limit rates", "7,000 sq ft luxury lodge", "Gourmet Cajun chef on site"],
tags: ["Featured", "Verified"]
},

{
id: "swc-sportsmans-lodge-la",
name: "SWC Sportsmans Lodge at Venice",
verified: true,
city: "Venice",
state: "LA",
stateFull: "Louisiana",
lat: 29.2700,
lng: -89.3700,
website: "https://www.getducks.com/ushunts/louisiana-duck-hunting-coastal-marsh/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – mid Jan" },
priceStarting: 600,
priceNotes: "All-inclusive; sleeps up to 20",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Hunts over 10 square miles of premium exclusive coastal marsh leases south of New Orleans.",
highlights: ["10 sq miles exclusive marsh leases", "3 steps from lodge to blind", "Trophy canvasbacks in January"],
tags: ["Featured", "Verified"]
},

{
id: "pecan-island-west-hunt-club-la",
name: "Pecan Island West Hunt Club",
verified: true,
city: "Pecan Island",
state: "LA",
stateFull: "Louisiana",
lat: 29.6541,
lng: -92.4543,
website: "https://www.piwesthunting.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept 20 – Sept 28", duck: "Nov 15 – Jan 25" },
priceStarting: 350,
priceNotes: "1,000+ acres private water-controlled marsh",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Over 60 years of duck hunting on 1,000+ acres of private, water-controlled marsh adjacent to White Lake.",
highlights: ["60+ years hunting same property", "1,000+ acres water-controlled marsh", "Adjacent to White Lake"],
tags: ["Verified"]
},

{
id: "southern-delta-outfitters-la",
name: "Southern Delta Outfitters",
verified: true,
city: "Southwest Louisiana",
state: "LA",
stateFull: "Louisiana",
lat: 30.2266,
lng: -93.2174,
website: "https://southerndeltaoutfitter.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 375,
priceNotes: "8 pit blinds scouted daily",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Founded in 2019 with a focus on five-star guided waterfowl experiences in Southwest Louisiana.",
highlights: ["8 scouted pit blinds", "Daily scouting for optimal placement", "Duck and goose hunting"],
tags: ["Verified"]
},

{
id: "shellshocked-guide-service-la",
name: "Shellshocked Guide Service",
verified: true,
city: "Central Louisiana",
state: "LA",
stateFull: "Louisiana",
lat: 31.2448,
lng: -92.4451,
website: "https://shellshockedguide.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – Jan" },
priceStarting: 450,
priceNotes: "All-inclusive corporate packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Licensed and insured Central Louisiana waterfowl outfitter hunting Louisiana Delta Plantation.",
highlights: ["Louisiana Delta Plantation access", "Catahoula Lake hunting", "Corporate all-inclusive packages"],
tags: ["Verified"]
},

{
id: "level-7-outdoors-la",
name: "Level 7 Outdoors",
verified: true,
city: "Catahoula Lake",
state: "LA",
stateFull: "Louisiana",
lat: 31.5000,
lng: -92.0000,
website: "https://level7outdoors.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { teal: "Sept", duck: "Nov – Jan" },
priceStarting: 350,
priceNotes: "Hunt Only or Hunt & Lodging packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–10 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Waterfront lodge on Larto Lake — part of the nearly 8,000-acre Saline/Larto complex.",
highlights: ["1,000+ decoy spreads", "Waterfront lodge on Larto Lake", "Airport pickup included"],
tags: ["Verified"]
},

{
id: "cajun-fishing-adventures-la",
name: "Cajun Fishing Adventures",
verified: true,
city: "Buras",
state: "LA",
stateFull: "Louisiana",
lat: 29.3600,
lng: -89.5300,
website: "https://www.cajunfishingadventures.com/",
phone: "(985) 785-9833",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan" },
priceStarting: 450,
priceNotes: "All-inclusive duck hunt + fishing combos",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–4 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Voted Top 5 fishing lodge in North America by Sportfishing Magazine. Hunting in Mississippi River Delta.",
highlights: ["Top 5 fishing lodge in North America", "Mississippi River Delta location", "Hunt + fishing all-inclusive combos"],
tags: ["Verified"]
},

{
id: "johnny-wink-megabucks-la",
name: "Johnny Wink's Megabucks Duck Guides",
verified: true,
city: "Natchitoches",
state: "LA",
stateFull: "Louisiana",
lat: 31.7607,
lng: -93.0863,
website: "https://johnnywink.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan (60 days)" },
priceStarting: 350,
priceNotes: "45 years guiding; fully booked each season",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Johnny Wink has guided duck hunts in Louisiana for 45 years. Stays fully booked every season.",
highlights: ["45 years guiding", "Fully booked every season", "International repeat clientele"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — MISSOURI
// ════════════════════════════════════════

{
id: "treasure-island-outfitters-mo",
name: "Treasure Island Outfitters",
verified: true,
city: "Southeast Missouri Bootheel",
state: "MO",
stateFull: "Missouri",
lat: 36.1500,
lng: -89.8000,
website: "https://treasureislandducks.com/",
phone: "(731) 487-3958",
email: "marshall@treasureislandducks.com",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { duck: "Late Nov – late Jan", goose: "Nov – Jan", snowGoose: "Jan – Feb" },
priceStarting: 300,
priceNotes: "Guided $300/person/day; All-inclusive $1,500/person for 3 days",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Southeast Missouri bootheel outfitter bordering Big Lake National Wildlife Refuge.",
highlights: ["Borders Big Lake NWR", "9,000 sq ft lodge — 12 private rooms", "Guided, all-inclusive, and DIY options"],
tags: ["Featured", "Verified"]
},

{
id: "rogers-goosedown-outfitters-mo",
name: "Rogers Goosedown Outfitters",
verified: true,
city: "Kennett",
state: "MO",
stateFull: "Missouri",
lat: 36.2362,
lng: -90.0521,
website: "https://rogersgoosedownoutfitters.com/",
phone: "(636) 698-3526",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan", snowGoose: "Spring conservation season" },
priceStarting: 225,
priceNotes: "$225/person per morning hunt; most affordable guided option",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Based in Kennett in the Missouri bootheel — known as 'waterfowl country.'",
highlights: ["$225/person per morning — most affordable", "150+ decoy spreads pre-set", "Dry pit blinds"],
tags: ["Verified"]
},

{
id: "fowl-lifestyle-outfitters-mo",
name: "Fowl Lifestyle Outfitters",
verified: true,
city: "Rives",
state: "MO",
stateFull: "Missouri",
lat: 36.2500,
lng: -89.9500,
website: "https://www.fowllifestyleoutfitters.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 300,
priceNotes: "Guided and daily pit lease options",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: true,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Southeast Missouri outfitter hunting over 500 to 3,000+ decoy spreads.",
highlights: ["500–3,000 decoy spreads", "Big Lake NWR proximity", "Five-star Elk Chute Lodge nearby"],
tags: ["Verified"]
},

{
id: "js-migrators-guide-service-mo",
name: "J&S Migrators Guide Service",
verified: true,
city: "Southeast Missouri",
state: "MO",
stateFull: "Missouri",
lat: 36.5000,
lng: -89.7000,
website: "https://duckhuntingguideservice.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan (specklebelly)", snowGoose: "Spring conservation season" },
priceStarting: 300,
priceNotes: "30+ years experience",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Over 30 years of guiding five-star waterfowl hunts in Southeast Missouri.",
highlights: ["30+ years guiding experience", "Exclusive access to prime SEMO fields", "Specklebelly and snow goose hunts"],
tags: ["Verified"]
},

{
id: "prairie-marsh-farm-mo",
name: "Prairie Marsh Farm",
verified: true,
city: "St. Charles County",
state: "MO",
stateFull: "Missouri",
lat: 38.8000,
lng: -90.7000,
website: "https://prairiemarshfarm.com/",
phone: "(636) 240-9426",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan (through the freeze)", goose: "Nov – Jan" },
priceStarting: 350,
priceNotes: "30 minutes from St. Louis",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–20 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Located just 30 minutes from St. Louis on the Mississippi Flyway.",
highlights: ["30 minutes from St. Louis", "Hunts through the freeze — late season", "Lodge sleeps 20 with private bathrooms"],
tags: ["Featured", "Verified"]
},

{
id: "habitat-flats-mo",
name: "Habitat Flats",
verified: true,
city: "Missouri",
state: "MO",
stateFull: "Missouri",
lat: 39.0000,
lng: -92.5000,
website: "https://www.habitatflats.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan" },
priceStarting: 600,
priceNotes: "All-inclusive; 5-star meals and lodge",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Recognized as North America's #1 waterfowl lodge network since 2008.",
highlights: ["North America's #1 waterfowl network", "Five-star meals and luxury lodging", "Canada (Saskatchewan) also available"],
tags: ["Featured", "Verified"]
},

{
id: "springville-creek-outfitters-mo",
name: "Springville Creek Outfitters",
verified: true,
city: "Missouri Bootheel",
state: "MO",
stateFull: "Missouri",
lat: 36.3000,
lng: -89.8000,
website: "https://www.springvillecreekoutfitters.com/",
phone: "(731) 697-3563",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan", snowGoose: "Spring conservation season" },
priceStarting: 275,
priceNotes: "Family-run 40+ years",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Family-run Missouri bootheel waterfowl outfitter in business for over 40 years.",
highlights: ["Family-run 40+ years", "Beginners and experts welcome", "Duck, goose, and snow goose"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// TURKEY + MULTI-SPECIES — NEBRASKA
// ════════════════════════════════════════

{
id: "heritage-outfitters-ne",
name: "Heritage Outfitters Nebraska",
verified: true,
city: "Curtis",
state: "NE",
stateFull: "Nebraska",
lat: 40.6333,
lng: -100.5142,
website: "https://heritageoutfittersne.com/",
phone: "",
email: "",
species: ["Turkey", "Whitetail Deer", "Mule Deer"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring", deer: "Oct – Jan" },
priceStarting: 1200,
priceNotes: "Turkey, Mule Deer, and Whitetail on 40,000+ acres private land",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Turkey hunts on 40,000+ acres of private western Nebraska land featuring Rios, Merriams, and hybrid turkeys.",
highlights: ["40,000+ acres private land for turkey", "OTC turkey tags — no draw", "Nebraska alfalfa and cedar country"],
tags: ["Featured", "Verified"]
},

{
id: "gobble-n-grunt-outfitters-ne",
name: "Gobble-N-Grunt Outfitters",
verified: true,
city: "Nebraska",
state: "NE",
stateFull: "Nebraska",
lat: 42.0000,
lng: -100.5000,
website: "https://huntthenorth.com/neturkey/",
phone: "",
email: "chris@gobblengrunt.com",
species: ["Turkey"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring (Merriam's)" },
priceStarting: 1000,
priceNotes: "2 and 3 day spring Merriam's turkey; guaranteed opportunity",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–3 days",
groupSize: "2–8 hunters",
successRate: "100%",
landType: "Private",
rating: 4.9,
description: "Operates three turkey camps on 150,000 acres. Claims more Merriam's turkey harvested than any other in the US.",
highlights: ["150,000 acres across 3 camps", "More Merriam's harvested here than anywhere", "Guaranteed opportunity", "OTC Nebraska tags"],
tags: ["Featured", "Verified"]
},

{
id: "struttin-thunder-outfitters-ne",
name: "Struttin Thunder Outfitters",
verified: true,
city: "Nebraska",
state: "NE",
stateFull: "Nebraska",
lat: 41.5000,
lng: -99.0000,
website: "https://struttinthunderoutfitters.com/",
phone: "",
email: "",
species: ["Turkey"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided", "Semi-Guided"],
seasons: { turkey: "Spring Merriam's" },
priceStarting: 900,
priceNotes: "Custom packages; fully and semi-guided available",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "2–4 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Founded 2004. 20+ years of Nebraska Merriam's turkey hunting. Uses Primos Double Bull blinds.",
highlights: ["Founded 2004 — 20+ years", "Diverse Nebraska terrain", "Fully and semi-guided"],
tags: ["Verified"]
},

{
id: "nichol-ridge-outfitters-ne",
name: "Nichol Ridge Outfitters",
verified: true,
city: "Nebraska / South Dakota",
state: "NE",
stateFull: "Nebraska",
lat: 42.5000,
lng: -100.0000,
website: "https://www.nroutfitters.net/",
phone: "",
email: "",
species: ["Turkey", "Whitetail Deer", "Mule Deer"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring Merriam's", deer: "Oct – Jan" },
priceStarting: 1100,
priceNotes: "Nebraska and South Dakota hunts; whitetail, mule deer, and Merriam's turkey",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–6 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Operations in both Nebraska and South Dakota. 30+ years of experience. Exceptional repeat client base.",
highlights: ["Nebraska + South Dakota operations", "30+ years experience", "OTC mule deer + whitetail combo"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// TURKEY + MULTI-SPECIES — OKLAHOMA
// ════════════════════════════════════════

{
id: "western-oklahoma-trophy-outfitters",
name: "Western Oklahoma Trophy Outfitters",
verified: true,
city: "Southwest / South Central Oklahoma",
state: "OK",
stateFull: "Oklahoma",
lat: 34.6036,
lng: -98.3959,
website: "https://www.wotohunts.com/",
phone: "",
email: "",
species: ["Turkey", "Whitetail Deer", "Elk", "Hog"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided", "Semi-Guided"],
seasons: { turkey: "Spring (Rio Grande) April – May", deer: "Oct – Jan", elk: "Sept – Nov", hog: "Year-round" },
priceStarting: 1500,
priceNotes: "40,000+ acres; two lodges in SW and south central Oklahoma",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–6 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Premier SW Oklahoma outfitter with access to 40,000+ acres managed by staff and a wildlife biologist.",
highlights: ["40,000+ acres with wildlife biologist", "Rio Grande turkey", "Elk + deer + turkey + hog", "Two Oklahoma lodge locations"],
tags: ["Featured", "Verified"]
},

{
id: "whiskey-creek-outfitters-ok",
name: "Whiskey Creek Outfitters",
verified: true,
city: "Oklahoma",
state: "OK",
stateFull: "Oklahoma",
lat: 35.5000,
lng: -97.5000,
website: "https://whiskeycreekoutfitter.com/",
phone: "",
email: "",
species: ["Waterfowl", "Turkey", "Whitetail Deer", "Hog"],
methods: ["Shotgun", "Firearm", "Archery", "Thermal/Night"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", turkey: "Spring and Fall", deer: "Oct – Jan", hog: "Year-round" },
priceStarting: 400,
priceNotes: "Duck, turkey, deer, and hog; thermal hog hunts can be added same-day after duck hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Oklahoma's premier multi-species outfitter offering duck, trophy deer, spring and fall turkey, and year-round thermal hog hunts.",
highlights: ["Duck + turkey + deer + hog all in one", "Thermal hog same-day after waterfowl", "Spring AND fall turkey"],
tags: ["Verified"]
},

{
id: "hunt-hickory-creek-ok",
name: "Hunt Hickory Creek",
verified: true,
city: "Northwest Oklahoma",
state: "OK",
stateFull: "Oklahoma",
lat: 36.5000,
lng: -98.5000,
website: "https://www.hunthickorycreek.com/",
phone: "",
email: "",
species: ["Turkey", "Whitetail Deer", "Hog"],
methods: ["Firearm", "Archery", "Thermal/Night"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring (Rio Grande) April – May", deer: "Oct – Jan", hog: "Year-round" },
priceStarting: 1200,
priceNotes: "NW Oklahoma Rio Grande turkey; deer and hog packages also available",
lodging: "Ranch",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Northwest Oklahoma outfitter with extensive oil and gas road access. Rio Grande turkeys in deep draws.",
highlights: ["Rio Grande turkey — NW Oklahoma", "Day and night thermal hog hunts", "Oil road access for any wind direction"],
tags: ["Verified"]
},

{
id: "tornado-valley-outfitters-ok",
name: "Tornado Valley Outfitters",
verified: true,
city: "SW Oklahoma / North Texas",
state: "OK",
stateFull: "Oklahoma",
lat: 34.1000,
lng: -98.5000,
website: "https://tornadovalleyoutfitters.com/",
phone: "",
email: "",
species: ["Waterfowl", "Turkey", "Whitetail Deer", "Hog", "Dove"],
methods: ["Shotgun", "Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan", goose: "Nov – Jan", crane: "Nov – Feb", turkey: "Spring", dove: "Sept", deer: "Oct – Jan", hog: "Year-round" },
priceStarting: 350,
priceNotes: "SW Oklahoma and North Texas; duck, goose, sandhill crane, dove, deer, turkey, and hog",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "1–4 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Offering one of the broadest species menus: duck, goose, sandhill crane, dove, whitetail deer, Rio Grande turkey, and hog.",
highlights: ["Sandhill crane hunting specialty", "7+ species available", "SW Oklahoma + North Texas", "Year-round operation"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// TURKEY (OSCEOLA) — FLORIDA
// ════════════════════════════════════════

{
id: "seminole-prairie-safaris-fl",
name: "Seminole Prairie Safaris",
verified: true,
city: "Lake Okeechobee",
state: "FL",
stateFull: "Florida",
lat: 26.9342,
lng: -80.7984,
website: "https://floridahuntingranch.com/",
phone: "(888) 785-9378",
email: "seminoleprairie@gmail.com",
species: ["Turkey", "Hog"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided", "Semi-Guided"],
seasons: { turkey: "Spring South Zone: March 7 – April 12; North Zone: March 21 – April 26", hog: "Year-round" },
priceStarting: 1000,
priceNotes: "2-day all-inclusive $1,000 min group of 4",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–4 days",
groupSize: "4–8 hunters",
successRate: "95%",
landType: "Private",
rating: 4.9,
description: "Family-run business for 30+ years north of Lake Okeechobee. 95% success rate for Osceola turkey.",
highlights: ["30+ years same family operation", "95% success rate", "20,000+ acres private land", "Osceola — Florida-only Grand Slam species"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// TURKEY + MULTI-SPECIES — MONTANA
// ════════════════════════════════════════

{
id: "musselshell-outfitters-mt",
name: "Musselshell Outfitters",
verified: true,
city: "Musselshell County",
state: "MT",
stateFull: "Montana",
lat: 46.5000,
lng: -108.2500,
website: "https://www.musselshelloutfitters.com/",
phone: "",
email: "",
species: ["Turkey", "Elk", "Mule Deer", "Whitetail Deer", "Pheasant"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { turkey: "Spring April 15 – May 31 (OTC tag)", elk: "Sept – Nov", pheasant: "Oct – Dec" },
priceStarting: 1850,
priceNotes: "1-bird 3-day turkey $1,850; 32nd year from same camp",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Celebrating 32nd year in business from the same hunting camp. True Merriam's turkeys — not hybrids.",
highlights: ["32nd year — same camp same area", "NWTF Patron Corporate Life Sponsor", "True Merriam's (not hybrids)", "OTC Montana turkey tags"],
tags: ["Featured", "Verified"]
},

{
id: "jj-guide-service-mt",
name: "J&J Guide Service",
verified: true,
city: "Ekalaka",
state: "MT",
stateFull: "Montana",
lat: 45.8883,
lng: -104.5522,
website: "https://www.jjguide.com/",
phone: "",
email: "",
species: ["Turkey", "Elk", "Mule Deer", "Whitetail Deer", "Antelope", "Waterfowl", "Pheasant"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring Merriam's", elk: "Sept – Nov", antelope: "Aug – Sept", waterfowl: "Oct – Jan", pheasant: "Oct – Dec" },
priceStarting: 1500,
priceNotes: "Lodge-based turkey hunts from Ekalaka MT; also elk, deer, antelope, upland, and waterfowl",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Southeastern Montana outfitter offering 7 species. Spring Merriam's turkey known for being the most vocal subspecies.",
highlights: ["7 species available in one outfitter", "Spring Merriam's spot-and-call", "License application assistance"],
tags: ["Verified"]
},

{
id: "lone-wolf-guide-service-mt",
name: "Lone Wolf Guide Service",
verified: true,
city: "Livingston",
state: "MT",
stateFull: "Montana",
lat: 45.6619,
lng: -110.5605,
website: "https://www.lonewolfguides.com/",
phone: "",
email: "",
species: ["Turkey", "Elk"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring Merriam's (private Montana ranches)", elk: "Sept – Nov" },
priceStarting: 1500,
priceNotes: "Private ranch turkey and elk near Livingston and Yellowstone",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–6 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Family-owned and operated, second-generation Montana outfitter (MT Licensed #6049) north of Yellowstone.",
highlights: ["MT Licensed Outfitter #6049", "2nd generation Montana native", "North of Yellowstone National Park"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// TURKEY — NEW MEXICO (MERRIAM'S / GRAND SLAM)
// ════════════════════════════════════════

{
id: "sierra-blanca-outfitters-nm",
name: "Sierra Blanca Outfitters",
verified: true,
city: "Holman",
state: "NM",
stateFull: "New Mexico",
lat: 36.0000,
lng: -105.3000,
website: "https://www.sierrablancaoutfitters.com/",
phone: "",
email: "",
species: ["Turkey", "Elk", "Mule Deer", "Whitetail Deer"],
methods: ["Firearm", "Archery", "Handgun"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring April 15 – May 15 (OTC tag)", elk: "Sept – Nov" },
priceStarting: 1200,
priceNotes: "Merriam's turkey OTC tag; 2-bird limit in NM spring",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Both",
rating: 4.8,
description: "Licensed New Mexico outfitter. Grand Slam destination — Merriam's is one of the four required subspecies.",
highlights: ["Grand Slam Merriam's specialist", "OTC New Mexico turkey tags", "Welcomes mobility-challenged hunters"],
tags: ["Featured", "Verified"]
},

{
id: "triple-c-outfitters-nm",
name: "Triple C Outfitters",
verified: true,
city: "Lincoln National Forest",
state: "NM",
stateFull: "New Mexico",
lat: 33.0000,
lng: -105.5000,
website: "https://www.nmelkhunts.com/turkey/",
phone: "(505) 506-6704",
email: "",
species: ["Turkey", "Elk", "Mule Deer"],
methods: ["Firearm", "Archery"],
tripTypes: ["Guided"],
seasons: { turkey: "Spring April 15 – May 15; Youth April 10-12", elk: "Sept – Nov" },
priceStarting: 2750,
priceNotes: "3-day 4-night all-inclusive $2,750 (2x1); 90% shot opportunity 5-year average",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3 days (4 nights)",
groupSize: "2–6 hunters",
successRate: "90%",
landType: "Public",
rating: 4.9,
description: "All hunts in Lincoln National Forest, New Mexico. 90% shot opportunity on mature Merriam's gobblers.",
highlights: ["90% shot opportunity — 5 year average", "Lincoln National Forest", "2-bird limit — Merriam's"],
tags: ["Featured", "Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — MINNESOTA
// ════════════════════════════════════════

{
id: "palisade-flats-hunt-club-mn",
name: "Palisade Flats Hunt Club",
verified: true,
city: "Palisade",
state: "MN",
stateFull: "Minnesota",
lat: 46.7167,
lng: -93.5000,
website: "https://palisadeflatshc.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { goose: "Sept – Oct", duck: "Oct – Nov", teal: "Sept" },
priceStarting: 500,
priceNotes: "4,000+ acres; chef-prepared meals; two lodges including Mallard Lodge built 2020",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–4 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "2.5 hours north of Minneapolis on 4,000+ acres including flooded rice paddies and Mississippi River bottoms.",
highlights: ["4,000+ acres including rice paddies", "North of Rice Lake NWR", "Sherp + Fat Truck transport", "Chef-prepared meals"],
tags: ["Featured", "Verified"]
},

{
id: "maxxed-out-guides-mn",
name: "Maxxed Out Guides & Lodge",
verified: true,
city: "Western Minnesota / South Dakota / Kansas",
state: "MN",
stateFull: "Minnesota",
lat: 45.3000,
lng: -96.5000,
website: "https://maxxedoutguides.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { goose: "Sept – Oct", duck: "Oct – Nov", snowGoose: "Spring conservation season" },
priceStarting: 400,
priceNotes: "Lodging included in MN and SD hunts; Benelli Experience Partner; guiding since 2007",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "2–4 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Operates across the Central and Mississippi Flyways — Minnesota, South Dakota, and Kansas.",
highlights: ["Operates across MN, SD, and KS", "In business since 2007", "Benelli Experience Partner"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// ELK SPECIALISTS — EASTERN KENTUCKY
// ════════════════════════════════════════

{
id: "lost-mountain-outfitters-ky",
name: "Lost Mountain Outfitters",
verified: true,
city: "Eastern Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 37.3000,
lng: -82.9000,
website: "http://www.lostmountainoutfitters.com/",
phone: "",
email: "",
species: ["Elk", "Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { elk: "Draw required", deer: "Sept – Jan", turkey: "Spring April – May" },
priceStarting: 4500,
priceNotes: "Elk guided hunts $4,500+",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Kentucky's premiere elk, deer, and turkey outfitter in the 16-county elk restoration zone. Kentucky holds the highest elk population east of the Mississippi (~10,000 animals).",
highlights: ["Eastern KY elk restoration zone — 16 counties", "Largest elk herd east of the Mississippi", "Field to freezer full service"],
tags: ["Featured", "Verified"]
},

{
id: "grace-elk-outfitters-ky",
name: "Grace Elk Outfitters",
verified: true,
city: "Eastern Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 37.2500,
lng: -83.2000,
website: "https://www.graceelkoutfitters.com/",
phone: "",
email: "",
species: ["Elk", "Bear", "Turkey"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { elk: "Draw required", bear: "Fall", turkey: "Spring and fall" },
priceStarting: 4500,
priceNotes: "Full service camp with cabins and RV sites",
lodging: "Cabin",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Full-service Eastern Kentucky outfitter specializing in elk hunting, bear hunting, and spring turkey. Camp features cabins and RV sites.",
highlights: ["Elk + bear + turkey specialty", "Cabins and RV sites at camp", "Field-to-table operation"],
tags: ["Verified"]
},

{
id: "kentucky-bulls-and-beards-ky",
name: "Kentucky Bulls and Beards Guide Service",
verified: true,
city: "Lily",
state: "KY",
stateFull: "Kentucky",
lat: 37.0700,
lng: -84.1100,
website: "https://www.kentuckybullsandbeardsguideservice.com/",
phone: "",
email: "",
species: ["Elk", "Turkey"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { elk: "Draw required", turkey: "Spring" },
priceStarting: 4500,
priceNotes: "President of Kentucky Elk Guide Association (KEGA)",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–4 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Kentucky Licensed Commercial Hunting Guide and licensed taxidermist. President of the Kentucky Elk Guide Association (KEGA).",
highlights: ["President of Kentucky Elk Guide Association", "Kentucky Licensed Commercial Guide", "State and federal licensed taxidermist"],
tags: ["Featured", "Verified"]
},

{
id: "kentucky-wild-outdoors-ky",
name: "Kentucky Wild Outdoors",
verified: true,
city: "Lexington area",
state: "KY",
stateFull: "Kentucky",
lat: 38.0406,
lng: -84.5037,
website: "https://www.kentuckywildoutdoors.com/",
phone: "",
email: "",
species: ["Elk"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { elk: "Draw required" },
priceStarting: 4500,
priceNotes: "50+ years experience; charter member Kentucky Elk Guide Association",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "5–7 days",
groupSize: "1–2 hunters",
successRate: "",
landType: "Both",
rating: 4.9,
description: "Owner-guide Bill Carman has over 50 years hunting experience. Charter member of Kentucky Elk Guide Association. Former RMEF Regional Director.",
highlights: ["50+ years KY hunting experience", "Former RMEF Regional Director", "Charter member Kentucky Elk Guide Association"],
tags: ["Featured", "Verified"]
},

{
id: "triple-crown-outfitters-ky",
name: "Triple Crown Outfitters",
verified: true,
city: "Jamestown",
state: "KY",
stateFull: "Kentucky",
lat: 36.9900,
lng: -85.0700,
website: "https://triplecrownoutfitters.net/",
phone: "",
email: "",
species: ["Elk", "Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided", "Self-Guided"],
seasons: { elk: "Draw required", deer: "Sept – Jan", turkey: "Spring" },
priceStarting: 2500,
priceNotes: "6,000+ acres KY and TN; max 10 hunters per hunt",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–6 days",
groupSize: "2–10 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Founded by Whitney — a rare female hunting guide. Operations span 6,000+ acres in Kentucky and Tennessee. Youth and family friendly.",
highlights: ["Female-owned and operated outfitter", "6,000+ acres KY and TN", "Max 10 hunters for quality"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// WESTERN KENTUCKY — WHITETAIL + TURKEY + WATERFOWL
// ════════════════════════════════════════

{
id: "premier-outfitters-ky",
name: "Premier Outfitters",
verified: true,
city: "Western Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 37.0000,
lng: -87.5000,
website: "https://premieroutfitters.com/",
phone: "(864) 938-8699",
email: "",
species: ["Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring" },
priceStarting: 2500,
priceNotes: "17+ years; named 'Dream Camp' by Deer & Deer Hunting magazine",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "In operation since 2008. Named 'Dream Camp' by Deer & Deer Hunting magazine. One of the top bow-hunting destinations for whitetail in the country.",
highlights: ["Named 'Dream Camp' by Deer & Deer Hunting magazine", "17+ years in operation", "Top bow-hunting destination nationally"],
tags: ["Featured", "Verified"]
},

{
id: "southern-whitetail-outfitters-ky",
name: "Southern Whitetail Outfitters",
verified: true,
city: "Southwestern Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 36.8500,
lng: -87.4000,
website: "https://www.southernwhitetailoutfitters.com/",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring" },
priceStarting: 2200,
priceNotes: "9,000+ acres; max 12 hunters per camp",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Over 9,000 acres of intensely managed land in Southwestern Kentucky hunting the top deer counties.",
highlights: ["9,000+ acres SW Kentucky", "Top KY deer counties", "Two lodges — max 12 hunters each"],
tags: ["Verified"]
},

{
id: "whitetail-heaven-outfitters-ky",
name: "Whitetail Heaven Outfitters",
verified: true,
city: "Central Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 37.8393,
lng: -84.2700,
website: "https://whitetailheavenoutfitters.com/",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader", "Crossbow"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring" },
priceStarting: 2500,
priceNotes: "25,000+ acres; 21+ years; handicap accessible",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–16 hunters",
successRate: "",
landType: "Private",
rating: 4.9,
description: "Over 21 years and 25,000+ intensely managed acres. Kentucky holds the 6th biggest typical buck ever harvested in the world.",
highlights: ["21+ years operation", "25,000+ acres KY, OH, and IN", "Handicap accessible"],
tags: ["Featured", "Verified"]
},

{
id: "west-kentucky-buck-co-ky",
name: "West Kentucky Buck Co.",
verified: true,
city: "Western Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 37.0000,
lng: -88.0000,
website: "https://westkentuckybuckco.com/",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey", "Waterfowl"],
methods: ["Rifle", "Archery", "Muzzleloader", "Shotgun"],
tripTypes: ["Guided", "Semi-Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring", waterfowl: "Oct – Jan" },
priceStarting: 2000,
priceNotes: "KY deer and turkey; also Oklahoma whitetail; Canada waterfowl hunts",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–6 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Western Kentucky outfitter offering full-service guided and semi-guided whitetail, turkey, and waterfowl hunting.",
highlights: ["KY deer + turkey + waterfowl", "Oklahoma whitetail also available", "Canada goose Saskatchewan hunts"],
tags: ["Verified"]
},

{
id: "western-kentucky-outdoors-ky",
name: "Western Kentucky Outdoors",
verified: true,
city: "Slaughters",
state: "KY",
stateFull: "Kentucky",
lat: 37.5200,
lng: -87.5100,
website: "http://westernkentuckyoutdoors.com/",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey", "Waterfowl"],
methods: ["Rifle", "Archery", "Muzzleloader", "Shotgun"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring", waterfowl: "Oct – Jan" },
priceStarting: 175,
priceNotes: "Waterfowl $175–$250 per hunt; one of the most affordable in the region",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–5 days",
groupSize: "2–10 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Western Kentucky multi-species outfitter. Waterfowl hunts from $175 — most affordable guided duck option in the region.",
highlights: ["Waterfowl from $175/hunt", "15+ duck and goose species", "Pit, layout, boat, flooded timber"],
tags: ["Verified"]
},

{
id: "diamond-whitetails-ky",
name: "Diamond Whitetails",
verified: true,
city: "Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 37.5000,
lng: -85.7000,
website: "https://diamondwhitetails.com/",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan" },
priceStarting: 2200,
priceNotes: "34% harvest rate, 75% opportunity rate; 85% hunter return rate",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–8 hunters",
successRate: "34% harvest / 75% opportunity",
landType: "Private",
rating: 4.8,
description: "Known for exceptional transparency — publicly reports 34% harvest rate. 85% of hunters return year after year.",
highlights: ["85% hunter return rate", "34% harvest / 75% opportunity", "Full-time professional guides only"],
tags: ["Verified"]
},

{
id: "bluegrass-whitetail-outfitters-ky",
name: "Bluegrass Whitetail Outfitters",
verified: true,
city: "Harned",
state: "KY",
stateFull: "Kentucky",
lat: 37.7800,
lng: -86.4300,
website: "https://bluegrasswhitetailoutfitters.com/",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan" },
priceStarting: 1800,
priceNotes: "Small local outfitter; lake lodging; Western Kentucky farms",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "3–5 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "Small, local Western Kentucky outfitter offering a genuine rural hunting experience. Lake lodging with amenities.",
highlights: ["Small local rural operation", "Lake lodge amenities", "Western Kentucky private farms"],
tags: ["Verified"]
},

{
id: "jonathan-creek-outfitters-ky",
name: "Jonathan Creek Outfitters",
verified: true,
city: "Western Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 36.9000,
lng: -88.2000,
website: "http://www.jonathancreekoutfitters.com/",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { deer: "Archery, muzzleloader, and rifle" },
priceStarting: 1800,
priceNotes: "4-5 day hunts; 1-on-1 guide service; meals, lodging, transportation included",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–5 days",
groupSize: "1–6 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "Western Kentucky outfitter offering 4–5 day packages with 1-on-1 guide service, lodging, and transportation.",
highlights: ["1-on-1 guide service", "Evening feast nightly", "Fishing combo available"],
tags: ["Verified"]
},

{
id: "whitetail-hunting-kentucky-ky",
name: "Whitetail Hunting Kentucky",
verified: true,
city: "Northeastern Kentucky",
state: "KY",
stateFull: "Kentucky",
lat: 38.2000,
lng: -83.5000,
website: "https://whitetailhuntingkentucky.com/",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader", "Crossbow"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring" },
priceStarting: 2200,
priceNotes: "130-inch minimum; drone and dog tracking available",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Northeastern Kentucky all-inclusive outfitter with strict 130-inch antler minimum. Offers drone and dog tracking.",
highlights: ["130-inch antler minimum enforced", "Drone + dog tracking for wounded game", "Velvet archery through late muzzleloader"],
tags: ["Verified"]
},

{
id: "salt-river-outfitters-ky",
name: "Salt River Outfitters",
verified: true,
city: "Bourbon Trail area",
state: "KY",
stateFull: "Kentucky",
lat: 37.9000,
lng: -85.1000,
website: "https://saltriverhunts.com/",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { deer: "Archery and rifle seasons" },
priceStarting: 2000,
priceNotes: "Located on the Kentucky Bourbon Trail; distillery tours available",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–10 hunters",
successRate: "",
landType: "Private",
rating: 4.8,
description: "Kentucky whitetail outfitter located on the Bourbon Trail with distilleries within 30 minutes. Consistent 5-star reviews.",
highlights: ["On the Kentucky Bourbon Trail", "Distillery tours can be arranged", "Consistent 5-star reviews"],
tags: ["Verified"]
},

{
id: "sunrise-outfitters-ky",
name: "Sunrise Outfitters",
verified: true,
city: "Cynthiana",
state: "KY",
stateFull: "Kentucky",
lat: 38.3900,
lng: -84.2900,
website: "https://sunrisedeerhunt.com/",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey", "Pheasant"],
methods: ["Rifle", "Archery", "Shotgun"],
tripTypes: ["Guided"],
seasons: { deer: "Sept – Jan", turkey: "Spring", pheasant: "Fall/Winter" },
priceStarting: 1800,
priceNotes: "45 min from Louisville or Cincinnati; 3 cabins; corporate retreats",
lodging: "Cabin",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "3–7 days",
groupSize: "2–12 hunters",
successRate: "",
landType: "Private",
rating: 4.7,
description: "Located 45 minutes from both Louisville and Cincinnati. Three cozy cabins. Offers deer, turkey, and pheasant hunting.",
highlights: ["45 min from Louisville or Cincinnati", "Deer + turkey + pheasant", "Corporate retreats welcome"],
tags: ["Verified"]
},

// ════════════════════════════════════════
// WATERFOWL — KENTUCKY
// ════════════════════════════════════════

{
id: "kentucky-bayou-outdoors-ky",
name: "Kentucky Bayou Outdoors",
verified: true,
city: "Hickman",
state: "KY",
stateFull: "Kentucky",
lat: 36.5700,
lng: -89.1900,
website: "https://www.kentuckybayou.com/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Nov – Jan" },
priceStarting: 300,
priceNotes: "Reelfoot Lake adjacent; guide started at age 7",
lodging: "Lodge",
lodgingIncluded: false,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Both",
rating: 4.7,
description: "Based in Hickman, KY at the confluence of the Mississippi River and Reelfoot Lake country. Owner started guiding at age 7.",
highlights: ["Reelfoot Lake area duck country", "Owner guided since age 7", "Mississippi River bottomlands"],
tags: ["Verified"]
},

{
id: "fins-to-feathers-ky",
name: "Fins to Feathers Outfitters",
verified: true,
city: "Grand Rivers",
state: "KY",
stateFull: "Kentucky",
lat: 37.0000,
lng: -88.2300,
website: "https://finstofeathers.net/",
phone: "",
email: "",
species: ["Waterfowl"],
methods: ["Shotgun"],
tripTypes: ["Guided"],
seasons: { duck: "Late Nov – Jan" },
priceStarting: 300,
priceNotes: "Pontoon blinds and layout boats on Kentucky Lake and Lake Barkley",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: false,
tripLength: "1–3 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Public",
rating: 4.7,
description: "Guided diver duck hunts on Kentucky Lake and Lake Barkley. Specialty in canvasback and redhead.",
highlights: ["Kentucky Lake + Lake Barkley", "Canvasback + redhead specialty", "Pontoon blinds and layout boats"],
tags: ["Verified"]
},

{
id: "kentucky-trophy-deer-ky",
name: "Kentucky Trophy Deer, LLC",
verified: true,
city: "Olaton",
state: "KY",
stateFull: "Kentucky",
lat: 37.3800,
lng: -86.7800,
website: "https://www.guidefitter.com/hunting/united-states-kentucky",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { deer: "Archery through late muzzleloader" },
priceStarting: 2500,
priceNotes: "Family-owned; rolling hills of Western KY; carefully managed deer bloodlines",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–6 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Family-owned and operated in the rolling hills of Western Kentucky. Carefully managed bloodlines for trophy quality.",
highlights: ["Carefully managed deer bloodlines", "Rolling hills Western Kentucky", "Family-owned and operated"],
tags: ["Verified"]
},

{
id: "crofton-outfitter-ky",
name: "Crofton Hunt Club",
verified: true,
city: "Crofton",
state: "KY",
stateFull: "Kentucky",
lat: 36.8700,
lng: -87.4800,
website: "https://www.guidefitter.com/hunting/united-states-kentucky",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery"],
tripTypes: ["Guided"],
seasons: { deer: "Rut season specialty", turkey: "Spring" },
priceStarting: 2000,
priceNotes: "Beautiful Western Kentucky; big mature bucks and gobbling turkeys",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–5 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Western Kentucky outfitter near Crofton offering guided whitetail and spring turkey hunts. Rut season rifle hunts are the specialty.",
highlights: ["Western KY rut season specialty", "Mature bucks + spring turkey", "Southern hospitality"],
tags: ["Verified"]
},

{
id: "burkesville-whitetail-ky",
name: "Burkesville Trophy Whitetail",
verified: true,
city: "Burkesville",
state: "KY",
stateFull: "Kentucky",
lat: 36.7900,
lng: -85.3700,
website: "https://www.guidefitter.com/hunting/united-states-kentucky",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Semi-Guided"],
seasons: { deer: "Velvet archery through rifle rut" },
priceStarting: 1500,
priceNotes: "Semi-guided; 4-day 5-night velvet archery and rut rifle packages",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–5 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.5,
description: "South Central Kentucky outfitter near Burkesville offering semi-guided trophy whitetail hunts. Velvet archery specialty.",
highlights: ["Velvet archery specialty", "River bottoms and forested ridges", "No hidden fees"],
tags: ["Verified"]
},

{
id: "liberty-whitetail-ky",
name: "Liberty Whitetail Outfitters",
verified: true,
city: "Liberty",
state: "KY",
stateFull: "Kentucky",
lat: 37.3200,
lng: -84.9400,
website: "https://www.guidefitter.com/hunting/united-states-kentucky",
phone: "",
email: "",
species: ["Whitetail Deer", "Turkey"],
methods: ["Rifle", "Archery", "Muzzleloader"],
tripTypes: ["Guided"],
seasons: { deer: "4-day 5-night all seasons", turkey: "Youth and regular spring season" },
priceStarting: 1800,
priceNotes: "All prices include meals, lodging, guide — no hidden fees",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "2–5 days",
groupSize: "1–8 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Central Kentucky outfitter offering all-inclusive whitetail and turkey hunts. Youth turkey hunts include adult companion. No hidden fees.",
highlights: ["No hidden fees — transparent pricing", "Youth turkey hunts", "All-inclusive 4-day packages"],
tags: ["Verified"]
},

{
id: "hopkinsville-rifle-rut-ky",
name: "Hopkinsville Rut Hunts",
verified: true,
city: "Hopkinsville",
state: "KY",
stateFull: "Kentucky",
lat: 36.8656,
lng: -87.4886,
website: "https://www.guidefitter.com/hunting/united-states-kentucky",
phone: "",
email: "",
species: ["Whitetail Deer"],
methods: ["Rifle"],
tripTypes: ["Guided"],
seasons: { deer: "Rifle rut season — peak November" },
priceStarting: 2200,
priceNotes: "Western Kentucky rifle rut specialty; lodging and meals included",
lodging: "Lodge",
lodgingIncluded: true,
mealsIncluded: true,
tripLength: "4–5 days",
groupSize: "2–8 hunters",
successRate: "",
landType: "Private",
rating: 4.6,
description: "Western Kentucky rifle rut deer hunting near Hopkinsville — one of Kentucky's top deer-producing regions.",
highlights: ["Rifle rut season specialty", "Hopkinsville — top KY deer county", "Peak November rut timing"],
tags: ["Verified"]
}

];

// Export for use in site
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { OUTFITTERS };
}

// Make globally available (browser only)
if (typeof window !== 'undefined') {
  window.OUTFITTERS = OUTFITTERS;
}